(IN-PACKAGE :XCLHB)

(DEFINE-STRUCT CHAR2B ((CARD8 BYTE1) (CARD8 BYTE2)))

(PROGN (EXPORT 'WINDOW) (DEFTYPE WINDOW () 'XID))

(PROGN (EXPORT 'PIXMAP) (DEFTYPE PIXMAP () 'XID))

(PROGN (EXPORT 'CURSOR) (DEFTYPE CURSOR () 'XID))

(PROGN (EXPORT 'FONT) (DEFTYPE FONT () 'XID))

(PROGN (EXPORT 'GCONTEXT) (DEFTYPE GCONTEXT () 'XID))

(PROGN (EXPORT 'COLORMAP) (DEFTYPE COLORMAP () 'XID))

(PROGN (EXPORT 'ATOM) (DEFTYPE ATOM () 'XID))

(PROGN (EXPORT 'DRAWABLE) (DEFTYPE DRAWABLE () '(OR WINDOW PIXMAP)))

(PROGN (EXPORT 'FONTABLE) (DEFTYPE FONTABLE () '(OR FONT GCONTEXT)))

(PROGN (EXPORT 'BOOL32) (DEFTYPE BOOL32 () 'CARD32))

(PROGN (EXPORT 'VISUALID) (DEFTYPE VISUALID () 'CARD32))

(PROGN (EXPORT 'TIMESTAMP) (DEFTYPE TIMESTAMP () 'CARD32))

(PROGN (EXPORT 'KEYSYM) (DEFTYPE KEYSYM () 'CARD32))

(PROGN (EXPORT 'KEYCODE) (DEFTYPE KEYCODE () 'CARD8))

(PROGN (EXPORT 'KEYCODE32) (DEFTYPE KEYCODE32 () 'CARD32))

(PROGN (EXPORT 'BUTTON) (DEFTYPE BUTTON () 'CARD8))

(DEFINE-STRUCT POINT ((INT16 X) (INT16 Y)))

(DEFINE-STRUCT RECTANGLE ((INT16 X) (INT16 Y) (CARD16 WIDTH) (CARD16 HEIGHT)))

(DEFINE-STRUCT ARC
 ((INT16 X) (INT16 Y) (CARD16 WIDTH) (CARD16 HEIGHT) (INT16 ANGLE1)
  (INT16 ANGLE2)))

(DEFINE-STRUCT FORMAT
 ((CARD8 DEPTH) (CARD8 BITS-PER-PIXEL) (CARD8 SCANLINE-PAD) (PAD BYTES 5)))

(PROGN
 (EXPORT '+VISUAL-CLASS--STATIC-GRAY+)
 (DEFCONSTANT +VISUAL-CLASS--STATIC-GRAY+ 0))

(PROGN
 (EXPORT '+VISUAL-CLASS--GRAY-SCALE+)
 (DEFCONSTANT +VISUAL-CLASS--GRAY-SCALE+ 1))

(PROGN
 (EXPORT '+VISUAL-CLASS--STATIC-COLOR+)
 (DEFCONSTANT +VISUAL-CLASS--STATIC-COLOR+ 2))

(PROGN
 (EXPORT '+VISUAL-CLASS--PSEUDO-COLOR+)
 (DEFCONSTANT +VISUAL-CLASS--PSEUDO-COLOR+ 3))

(PROGN
 (EXPORT '+VISUAL-CLASS--TRUE-COLOR+)
 (DEFCONSTANT +VISUAL-CLASS--TRUE-COLOR+ 4))

(PROGN
 (EXPORT '+VISUAL-CLASS--DIRECT-COLOR+)
 (DEFCONSTANT +VISUAL-CLASS--DIRECT-COLOR+ 5))

(DEFINE-STRUCT VISUALTYPE
 ((VISUALID VISUAL-ID) (CARD8 CLASS) (CARD8 BITS-PER-RGB-VALUE)
  (CARD16 COLORMAP-ENTRIES) (CARD32 RED-MASK) (CARD32 GREEN-MASK)
  (CARD32 BLUE-MASK) (PAD BYTES 4)))

(DEFINE-STRUCT DEPTH
 ((CARD8 DEPTH) (PAD BYTES 1) (CARD16 VISUALS-LEN) (PAD BYTES 4)
  (LIST VISUALTYPE VISUALS-LEN VISUALS)))

(PROGN (EXPORT '+EVENT-MASK--NO-EVENT+) (DEFCONSTANT +EVENT-MASK--NO-EVENT+ 0))

(PROGN
 (EXPORT '+EVENT-MASK--KEY-PRESS+)
 (DEFCONSTANT +EVENT-MASK--KEY-PRESS+ 0))

(PROGN
 (EXPORT '+EVENT-MASK--KEY-RELEASE+)
 (DEFCONSTANT +EVENT-MASK--KEY-RELEASE+ 1))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON-PRESS+)
 (DEFCONSTANT +EVENT-MASK--BUTTON-PRESS+ 2))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON-RELEASE+)
 (DEFCONSTANT +EVENT-MASK--BUTTON-RELEASE+ 3))

(PROGN
 (EXPORT '+EVENT-MASK--ENTER-WINDOW+)
 (DEFCONSTANT +EVENT-MASK--ENTER-WINDOW+ 4))

(PROGN
 (EXPORT '+EVENT-MASK--LEAVE-WINDOW+)
 (DEFCONSTANT +EVENT-MASK--LEAVE-WINDOW+ 5))

(PROGN
 (EXPORT '+EVENT-MASK--POINTER-MOTION+)
 (DEFCONSTANT +EVENT-MASK--POINTER-MOTION+ 6))

(PROGN
 (EXPORT '+EVENT-MASK--POINTER-MOTION-HINT+)
 (DEFCONSTANT +EVENT-MASK--POINTER-MOTION-HINT+ 7))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON1MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON1MOTION+ 8))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON2MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON2MOTION+ 9))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON3MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON3MOTION+ 10))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON4MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON4MOTION+ 11))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON5MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON5MOTION+ 12))

(PROGN
 (EXPORT '+EVENT-MASK--BUTTON-MOTION+)
 (DEFCONSTANT +EVENT-MASK--BUTTON-MOTION+ 13))

(PROGN
 (EXPORT '+EVENT-MASK--KEYMAP-STATE+)
 (DEFCONSTANT +EVENT-MASK--KEYMAP-STATE+ 14))

(PROGN (EXPORT '+EVENT-MASK--EXPOSURE+) (DEFCONSTANT +EVENT-MASK--EXPOSURE+ 15))

(PROGN
 (EXPORT '+EVENT-MASK--VISIBILITY-CHANGE+)
 (DEFCONSTANT +EVENT-MASK--VISIBILITY-CHANGE+ 16))

(PROGN
 (EXPORT '+EVENT-MASK--STRUCTURE-NOTIFY+)
 (DEFCONSTANT +EVENT-MASK--STRUCTURE-NOTIFY+ 17))

(PROGN
 (EXPORT '+EVENT-MASK--RESIZE-REDIRECT+)
 (DEFCONSTANT +EVENT-MASK--RESIZE-REDIRECT+ 18))

(PROGN
 (EXPORT '+EVENT-MASK--SUBSTRUCTURE-NOTIFY+)
 (DEFCONSTANT +EVENT-MASK--SUBSTRUCTURE-NOTIFY+ 19))

(PROGN
 (EXPORT '+EVENT-MASK--SUBSTRUCTURE-REDIRECT+)
 (DEFCONSTANT +EVENT-MASK--SUBSTRUCTURE-REDIRECT+ 20))

(PROGN
 (EXPORT '+EVENT-MASK--FOCUS-CHANGE+)
 (DEFCONSTANT +EVENT-MASK--FOCUS-CHANGE+ 21))

(PROGN
 (EXPORT '+EVENT-MASK--PROPERTY-CHANGE+)
 (DEFCONSTANT +EVENT-MASK--PROPERTY-CHANGE+ 22))

(PROGN
 (EXPORT '+EVENT-MASK--COLOR-MAP-CHANGE+)
 (DEFCONSTANT +EVENT-MASK--COLOR-MAP-CHANGE+ 23))

(PROGN
 (EXPORT '+EVENT-MASK--OWNER-GRAB-BUTTON+)
 (DEFCONSTANT +EVENT-MASK--OWNER-GRAB-BUTTON+ 24))

(PROGN
 (EXPORT '+BACKING-STORE--NOT-USEFUL+)
 (DEFCONSTANT +BACKING-STORE--NOT-USEFUL+ 0))

(PROGN
 (EXPORT '+BACKING-STORE--WHEN-MAPPED+)
 (DEFCONSTANT +BACKING-STORE--WHEN-MAPPED+ 1))

(PROGN
 (EXPORT '+BACKING-STORE--ALWAYS+)
 (DEFCONSTANT +BACKING-STORE--ALWAYS+ 2))

(DEFINE-STRUCT SCREEN
 ((WINDOW ROOT) (COLORMAP DEFAULT-COLORMAP) (CARD32 WHITE-PIXEL)
  (CARD32 BLACK-PIXEL) (CARD32 CURRENT-INPUT-MASKS) (CARD16 WIDTH-IN-PIXELS)
  (CARD16 HEIGHT-IN-PIXELS) (CARD16 WIDTH-IN-MILLIMETERS)
  (CARD16 HEIGHT-IN-MILLIMETERS) (CARD16 MIN-INSTALLED-MAPS)
  (CARD16 MAX-INSTALLED-MAPS) (VISUALID ROOT-VISUAL) (BYTE BACKING-STORES)
  (BOOL SAVE-UNDERS) (CARD8 ROOT-DEPTH) (CARD8 ALLOWED-DEPTHS-LEN)
  (LIST DEPTH ALLOWED-DEPTHS-LEN ALLOWED-DEPTHS)))

(DEFINE-STRUCT SETUP-REQUEST
 ((CARD8 BYTE-ORDER) (PAD BYTES 1) (CARD16 PROTOCOL-MAJOR-VERSION)
  (CARD16 PROTOCOL-MINOR-VERSION) (CARD16 AUTHORIZATION-PROTOCOL-NAME-LEN)
  (CARD16 AUTHORIZATION-PROTOCOL-DATA-LEN) (PAD BYTES 2)
  (LIST CHAR AUTHORIZATION-PROTOCOL-NAME-LEN AUTHORIZATION-PROTOCOL-NAME)
  (PAD ALIGN 4)
  (LIST CHAR AUTHORIZATION-PROTOCOL-DATA-LEN AUTHORIZATION-PROTOCOL-DATA)
  (PAD ALIGN 4)))

(DEFINE-STRUCT SETUP-FAILED
 ((CARD8 STATUS) (CARD8 REASON-LEN) (CARD16 PROTOCOL-MAJOR-VERSION)
  (CARD16 PROTOCOL-MINOR-VERSION) (CARD16 LENGTH)
  (LIST CHAR REASON-LEN REASON)))

(DEFINE-STRUCT SETUP-AUTHENTICATE
 ((CARD8 STATUS) (PAD BYTES 5) (CARD16 LENGTH) (LIST CHAR (* LENGTH 4) REASON)))

(PROGN
 (EXPORT '+IMAGE-ORDER--LSBFIRST+)
 (DEFCONSTANT +IMAGE-ORDER--LSBFIRST+ 0))

(PROGN
 (EXPORT '+IMAGE-ORDER--MSBFIRST+)
 (DEFCONSTANT +IMAGE-ORDER--MSBFIRST+ 1))

(DEFINE-STRUCT SETUP
 ((CARD8 STATUS) (PAD BYTES 1) (CARD16 PROTOCOL-MAJOR-VERSION)
  (CARD16 PROTOCOL-MINOR-VERSION) (CARD16 LENGTH) (CARD32 RELEASE-NUMBER)
  (CARD32 RESOURCE-ID-BASE) (CARD32 RESOURCE-ID-MASK)
  (CARD32 MOTION-BUFFER-SIZE) (CARD16 VENDOR-LEN)
  (CARD16 MAXIMUM-REQUEST-LENGTH) (CARD8 ROOTS-LEN) (CARD8 PIXMAP-FORMATS-LEN)
  (CARD8 IMAGE-BYTE-ORDER) (CARD8 BITMAP-FORMAT-BIT-ORDER)
  (CARD8 BITMAP-FORMAT-SCANLINE-UNIT) (CARD8 BITMAP-FORMAT-SCANLINE-PAD)
  (KEYCODE MIN-KEYCODE) (KEYCODE MAX-KEYCODE) (PAD BYTES 4)
  (LIST CHAR VENDOR-LEN VENDOR) (PAD ALIGN 4)
  (LIST FORMAT PIXMAP-FORMATS-LEN PIXMAP-FORMATS)
  (LIST SCREEN ROOTS-LEN ROOTS)))

(PROGN (EXPORT '+MOD-MASK--SHIFT+) (DEFCONSTANT +MOD-MASK--SHIFT+ 0))

(PROGN (EXPORT '+MOD-MASK--LOCK+) (DEFCONSTANT +MOD-MASK--LOCK+ 1))

(PROGN (EXPORT '+MOD-MASK--CONTROL+) (DEFCONSTANT +MOD-MASK--CONTROL+ 2))

(PROGN (EXPORT '+MOD-MASK--1+) (DEFCONSTANT +MOD-MASK--1+ 3))

(PROGN (EXPORT '+MOD-MASK--2+) (DEFCONSTANT +MOD-MASK--2+ 4))

(PROGN (EXPORT '+MOD-MASK--3+) (DEFCONSTANT +MOD-MASK--3+ 5))

(PROGN (EXPORT '+MOD-MASK--4+) (DEFCONSTANT +MOD-MASK--4+ 6))

(PROGN (EXPORT '+MOD-MASK--5+) (DEFCONSTANT +MOD-MASK--5+ 7))

(PROGN (EXPORT '+MOD-MASK--ANY+) (DEFCONSTANT +MOD-MASK--ANY+ 15))

(PROGN (EXPORT '+KEY-BUT-MASK--SHIFT+) (DEFCONSTANT +KEY-BUT-MASK--SHIFT+ 0))

(PROGN (EXPORT '+KEY-BUT-MASK--LOCK+) (DEFCONSTANT +KEY-BUT-MASK--LOCK+ 1))

(PROGN
 (EXPORT '+KEY-BUT-MASK--CONTROL+)
 (DEFCONSTANT +KEY-BUT-MASK--CONTROL+ 2))

(PROGN (EXPORT '+KEY-BUT-MASK--MOD1+) (DEFCONSTANT +KEY-BUT-MASK--MOD1+ 3))

(PROGN (EXPORT '+KEY-BUT-MASK--MOD2+) (DEFCONSTANT +KEY-BUT-MASK--MOD2+ 4))

(PROGN (EXPORT '+KEY-BUT-MASK--MOD3+) (DEFCONSTANT +KEY-BUT-MASK--MOD3+ 5))

(PROGN (EXPORT '+KEY-BUT-MASK--MOD4+) (DEFCONSTANT +KEY-BUT-MASK--MOD4+ 6))

(PROGN (EXPORT '+KEY-BUT-MASK--MOD5+) (DEFCONSTANT +KEY-BUT-MASK--MOD5+ 7))

(PROGN
 (EXPORT '+KEY-BUT-MASK--BUTTON1+)
 (DEFCONSTANT +KEY-BUT-MASK--BUTTON1+ 8))

(PROGN
 (EXPORT '+KEY-BUT-MASK--BUTTON2+)
 (DEFCONSTANT +KEY-BUT-MASK--BUTTON2+ 9))

(PROGN
 (EXPORT '+KEY-BUT-MASK--BUTTON3+)
 (DEFCONSTANT +KEY-BUT-MASK--BUTTON3+ 10))

(PROGN
 (EXPORT '+KEY-BUT-MASK--BUTTON4+)
 (DEFCONSTANT +KEY-BUT-MASK--BUTTON4+ 11))

(PROGN
 (EXPORT '+KEY-BUT-MASK--BUTTON5+)
 (DEFCONSTANT +KEY-BUT-MASK--BUTTON5+ 12))

(PROGN (EXPORT '+WINDOW--NONE+) (DEFCONSTANT +WINDOW--NONE+ 0))

(DEFINE-EVENT KEY-PRESS 2
 ((KEYCODE DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BOOL SAME-SCREEN) (PAD BYTES 1)))

(DEFINE-EVENT KEY-RELEASE 3
 ((KEYCODE DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BOOL SAME-SCREEN) (PAD BYTES 1)))

(PROGN (EXPORT '+BUTTON-MASK--1+) (DEFCONSTANT +BUTTON-MASK--1+ 8))

(PROGN (EXPORT '+BUTTON-MASK--2+) (DEFCONSTANT +BUTTON-MASK--2+ 9))

(PROGN (EXPORT '+BUTTON-MASK--3+) (DEFCONSTANT +BUTTON-MASK--3+ 10))

(PROGN (EXPORT '+BUTTON-MASK--4+) (DEFCONSTANT +BUTTON-MASK--4+ 11))

(PROGN (EXPORT '+BUTTON-MASK--5+) (DEFCONSTANT +BUTTON-MASK--5+ 12))

(PROGN (EXPORT '+BUTTON-MASK--ANY+) (DEFCONSTANT +BUTTON-MASK--ANY+ 15))

(DEFINE-EVENT BUTTON-PRESS 4
 ((BUTTON DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BOOL SAME-SCREEN) (PAD BYTES 1)))

(DEFINE-EVENT BUTTON-RELEASE 5
 ((BUTTON DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BOOL SAME-SCREEN) (PAD BYTES 1)))

(PROGN (EXPORT '+MOTION--NORMAL+) (DEFCONSTANT +MOTION--NORMAL+ 0))

(PROGN (EXPORT '+MOTION--HINT+) (DEFCONSTANT +MOTION--HINT+ 1))

(DEFINE-EVENT MOTION-NOTIFY 6
 ((BYTE DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BOOL SAME-SCREEN) (PAD BYTES 1)))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--ANCESTOR+)
 (DEFCONSTANT +NOTIFY-DETAIL--ANCESTOR+ 0))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--VIRTUAL+)
 (DEFCONSTANT +NOTIFY-DETAIL--VIRTUAL+ 1))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--INFERIOR+)
 (DEFCONSTANT +NOTIFY-DETAIL--INFERIOR+ 2))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--NONLINEAR+)
 (DEFCONSTANT +NOTIFY-DETAIL--NONLINEAR+ 3))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--NONLINEAR-VIRTUAL+)
 (DEFCONSTANT +NOTIFY-DETAIL--NONLINEAR-VIRTUAL+ 4))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--POINTER+)
 (DEFCONSTANT +NOTIFY-DETAIL--POINTER+ 5))

(PROGN
 (EXPORT '+NOTIFY-DETAIL--POINTER-ROOT+)
 (DEFCONSTANT +NOTIFY-DETAIL--POINTER-ROOT+ 6))

(PROGN (EXPORT '+NOTIFY-DETAIL--NONE+) (DEFCONSTANT +NOTIFY-DETAIL--NONE+ 7))

(PROGN (EXPORT '+NOTIFY-MODE--NORMAL+) (DEFCONSTANT +NOTIFY-MODE--NORMAL+ 0))

(PROGN (EXPORT '+NOTIFY-MODE--GRAB+) (DEFCONSTANT +NOTIFY-MODE--GRAB+ 1))

(PROGN (EXPORT '+NOTIFY-MODE--UNGRAB+) (DEFCONSTANT +NOTIFY-MODE--UNGRAB+ 2))

(PROGN
 (EXPORT '+NOTIFY-MODE--WHILE-GRABBED+)
 (DEFCONSTANT +NOTIFY-MODE--WHILE-GRABBED+ 3))

(DEFINE-EVENT ENTER-NOTIFY 7
 ((BYTE DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BYTE MODE) (BYTE SAME-SCREEN-FOCUS)))

(DEFINE-EVENT LEAVE-NOTIFY 8
 ((BYTE DETAIL) (TIMESTAMP TIME) (WINDOW ROOT) (WINDOW EVENT) (WINDOW CHILD)
  (INT16 ROOT-X) (INT16 ROOT-Y) (INT16 EVENT-X) (INT16 EVENT-Y) (CARD16 STATE)
  (BYTE MODE) (BYTE SAME-SCREEN-FOCUS)))

(DEFINE-EVENT FOCUS-IN 9
 ((BYTE DETAIL) (WINDOW EVENT) (BYTE MODE) (PAD BYTES 3)))

(DEFINE-EVENT FOCUS-OUT 10
 ((BYTE DETAIL) (WINDOW EVENT) (BYTE MODE) (PAD BYTES 3)))

(DEFINE-EVENT KEYMAP-NOTIFY 11 ((LIST CARD8 31 KEYS)))

(DEFINE-EVENT EXPOSE 12
 ((PAD BYTES 1) (WINDOW WINDOW) (CARD16 X) (CARD16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD16 COUNT) (PAD BYTES 2)))

(DEFINE-EVENT GRAPHICS-EXPOSURE 13
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (CARD16 X) (CARD16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD16 MINOR-OPCODE) (CARD16 COUNT) (CARD8 MAJOR-OPCODE)
  (PAD BYTES 3)))

(DEFINE-EVENT NO-EXPOSURE 14
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (CARD16 MINOR-OPCODE) (CARD8 MAJOR-OPCODE)
  (PAD BYTES 1)))

(PROGN
 (EXPORT '+VISIBILITY--UNOBSCURED+)
 (DEFCONSTANT +VISIBILITY--UNOBSCURED+ 0))

(PROGN
 (EXPORT '+VISIBILITY--PARTIALLY-OBSCURED+)
 (DEFCONSTANT +VISIBILITY--PARTIALLY-OBSCURED+ 1))

(PROGN
 (EXPORT '+VISIBILITY--FULLY-OBSCURED+)
 (DEFCONSTANT +VISIBILITY--FULLY-OBSCURED+ 2))

(DEFINE-EVENT VISIBILITY-NOTIFY 15
 ((PAD BYTES 1) (WINDOW WINDOW) (BYTE STATE) (PAD BYTES 3)))

(DEFINE-EVENT CREATE-NOTIFY 16
 ((PAD BYTES 1) (WINDOW PARENT) (WINDOW WINDOW) (INT16 X) (INT16 Y)
  (CARD16 WIDTH) (CARD16 HEIGHT) (CARD16 BORDER-WIDTH) (BOOL OVERRIDE-REDIRECT)
  (PAD BYTES 1)))

(DEFINE-EVENT DESTROY-NOTIFY 17 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW)))

(DEFINE-EVENT UNMAP-NOTIFY 18
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (BOOL FROM-CONFIGURE)
  (PAD BYTES 3)))

(DEFINE-EVENT MAP-NOTIFY 19
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (BOOL OVERRIDE-REDIRECT)
  (PAD BYTES 3)))

(DEFINE-EVENT MAP-REQUEST 20 ((PAD BYTES 1) (WINDOW PARENT) (WINDOW WINDOW)))

(DEFINE-EVENT REPARENT-NOTIFY 21
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (WINDOW PARENT) (INT16 X)
  (INT16 Y) (BOOL OVERRIDE-REDIRECT) (PAD BYTES 3)))

(DEFINE-EVENT CONFIGURE-NOTIFY 22
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (WINDOW ABOVE-SIBLING) (INT16 X)
  (INT16 Y) (CARD16 WIDTH) (CARD16 HEIGHT) (CARD16 BORDER-WIDTH)
  (BOOL OVERRIDE-REDIRECT) (PAD BYTES 1)))

(DEFINE-EVENT CONFIGURE-REQUEST 23
 ((BYTE STACK-MODE) (WINDOW PARENT) (WINDOW WINDOW) (WINDOW SIBLING) (INT16 X)
  (INT16 Y) (CARD16 WIDTH) (CARD16 HEIGHT) (CARD16 BORDER-WIDTH)
  (CARD16 VALUE-MASK)))

(DEFINE-EVENT GRAVITY-NOTIFY 24
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (INT16 X) (INT16 Y)))

(DEFINE-EVENT RESIZE-REQUEST 25
 ((PAD BYTES 1) (WINDOW WINDOW) (CARD16 WIDTH) (CARD16 HEIGHT)))

(PROGN (EXPORT '+PLACE--ON-TOP+) (DEFCONSTANT +PLACE--ON-TOP+ 0))

(PROGN (EXPORT '+PLACE--ON-BOTTOM+) (DEFCONSTANT +PLACE--ON-BOTTOM+ 1))

(DEFINE-EVENT CIRCULATE-NOTIFY 26
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (PAD BYTES 4) (BYTE PLACE)
  (PAD BYTES 3)))

(DEFINE-EVENT CIRCULATE-REQUEST 27
 ((PAD BYTES 1) (WINDOW EVENT) (WINDOW WINDOW) (PAD BYTES 4) (BYTE PLACE)
  (PAD BYTES 3)))

(PROGN (EXPORT '+PROPERTY--NEW-VALUE+) (DEFCONSTANT +PROPERTY--NEW-VALUE+ 0))

(PROGN (EXPORT '+PROPERTY--DELETE+) (DEFCONSTANT +PROPERTY--DELETE+ 1))

(DEFINE-EVENT PROPERTY-NOTIFY 28
 ((PAD BYTES 1) (WINDOW WINDOW) (ATOM ATOM) (TIMESTAMP TIME) (BYTE STATE)
  (PAD BYTES 3)))

(DEFINE-EVENT SELECTION-CLEAR 29
 ((PAD BYTES 1) (TIMESTAMP TIME) (WINDOW OWNER) (ATOM SELECTION)))

(PROGN (EXPORT '+TIME--CURRENT-TIME+) (DEFCONSTANT +TIME--CURRENT-TIME+ 0))

(PROGN (EXPORT '+ATOM--NONE+) (DEFCONSTANT +ATOM--NONE+ 0))

(PROGN (EXPORT '+ATOM--ANY+) (DEFCONSTANT +ATOM--ANY+ 0))

(PROGN (EXPORT '+ATOM--PRIMARY+) (DEFCONSTANT +ATOM--PRIMARY+ 1))

(PROGN (EXPORT '+ATOM--SECONDARY+) (DEFCONSTANT +ATOM--SECONDARY+ 2))

(PROGN (EXPORT '+ATOM--ARC+) (DEFCONSTANT +ATOM--ARC+ 3))

(PROGN (EXPORT '+ATOM--ATOM+) (DEFCONSTANT +ATOM--ATOM+ 4))

(PROGN (EXPORT '+ATOM--BITMAP+) (DEFCONSTANT +ATOM--BITMAP+ 5))

(PROGN (EXPORT '+ATOM--CARDINAL+) (DEFCONSTANT +ATOM--CARDINAL+ 6))

(PROGN (EXPORT '+ATOM--COLORMAP+) (DEFCONSTANT +ATOM--COLORMAP+ 7))

(PROGN (EXPORT '+ATOM--CURSOR+) (DEFCONSTANT +ATOM--CURSOR+ 8))

(PROGN (EXPORT '+ATOM--CUT-BUFFER0+) (DEFCONSTANT +ATOM--CUT-BUFFER0+ 9))

(PROGN (EXPORT '+ATOM--CUT-BUFFER1+) (DEFCONSTANT +ATOM--CUT-BUFFER1+ 10))

(PROGN (EXPORT '+ATOM--CUT-BUFFER2+) (DEFCONSTANT +ATOM--CUT-BUFFER2+ 11))

(PROGN (EXPORT '+ATOM--CUT-BUFFER3+) (DEFCONSTANT +ATOM--CUT-BUFFER3+ 12))

(PROGN (EXPORT '+ATOM--CUT-BUFFER4+) (DEFCONSTANT +ATOM--CUT-BUFFER4+ 13))

(PROGN (EXPORT '+ATOM--CUT-BUFFER5+) (DEFCONSTANT +ATOM--CUT-BUFFER5+ 14))

(PROGN (EXPORT '+ATOM--CUT-BUFFER6+) (DEFCONSTANT +ATOM--CUT-BUFFER6+ 15))

(PROGN (EXPORT '+ATOM--CUT-BUFFER7+) (DEFCONSTANT +ATOM--CUT-BUFFER7+ 16))

(PROGN (EXPORT '+ATOM--DRAWABLE+) (DEFCONSTANT +ATOM--DRAWABLE+ 17))

(PROGN (EXPORT '+ATOM--FONT+) (DEFCONSTANT +ATOM--FONT+ 18))

(PROGN (EXPORT '+ATOM--INTEGER+) (DEFCONSTANT +ATOM--INTEGER+ 19))

(PROGN (EXPORT '+ATOM--PIXMAP+) (DEFCONSTANT +ATOM--PIXMAP+ 20))

(PROGN (EXPORT '+ATOM--POINT+) (DEFCONSTANT +ATOM--POINT+ 21))

(PROGN (EXPORT '+ATOM--RECTANGLE+) (DEFCONSTANT +ATOM--RECTANGLE+ 22))

(PROGN
 (EXPORT '+ATOM--RESOURCE-MANAGER+)
 (DEFCONSTANT +ATOM--RESOURCE-MANAGER+ 23))

(PROGN (EXPORT '+ATOM--RGB-COLOR-MAP+) (DEFCONSTANT +ATOM--RGB-COLOR-MAP+ 24))

(PROGN (EXPORT '+ATOM--RGB-BEST-MAP+) (DEFCONSTANT +ATOM--RGB-BEST-MAP+ 25))

(PROGN (EXPORT '+ATOM--RGB-BLUE-MAP+) (DEFCONSTANT +ATOM--RGB-BLUE-MAP+ 26))

(PROGN
 (EXPORT '+ATOM--RGB-DEFAULT-MAP+)
 (DEFCONSTANT +ATOM--RGB-DEFAULT-MAP+ 27))

(PROGN (EXPORT '+ATOM--RGB-GRAY-MAP+) (DEFCONSTANT +ATOM--RGB-GRAY-MAP+ 28))

(PROGN (EXPORT '+ATOM--RGB-GREEN-MAP+) (DEFCONSTANT +ATOM--RGB-GREEN-MAP+ 29))

(PROGN (EXPORT '+ATOM--RGB-RED-MAP+) (DEFCONSTANT +ATOM--RGB-RED-MAP+ 30))

(PROGN (EXPORT '+ATOM--STRING+) (DEFCONSTANT +ATOM--STRING+ 31))

(PROGN (EXPORT '+ATOM--VISUALID+) (DEFCONSTANT +ATOM--VISUALID+ 32))

(PROGN (EXPORT '+ATOM--WINDOW+) (DEFCONSTANT +ATOM--WINDOW+ 33))

(PROGN (EXPORT '+ATOM--WM-COMMAND+) (DEFCONSTANT +ATOM--WM-COMMAND+ 34))

(PROGN (EXPORT '+ATOM--WM-HINTS+) (DEFCONSTANT +ATOM--WM-HINTS+ 35))

(PROGN
 (EXPORT '+ATOM--WM-CLIENT-MACHINE+)
 (DEFCONSTANT +ATOM--WM-CLIENT-MACHINE+ 36))

(PROGN (EXPORT '+ATOM--WM-ICON-NAME+) (DEFCONSTANT +ATOM--WM-ICON-NAME+ 37))

(PROGN (EXPORT '+ATOM--WM-ICON-SIZE+) (DEFCONSTANT +ATOM--WM-ICON-SIZE+ 38))

(PROGN (EXPORT '+ATOM--WM-NAME+) (DEFCONSTANT +ATOM--WM-NAME+ 39))

(PROGN
 (EXPORT '+ATOM--WM-NORMAL-HINTS+)
 (DEFCONSTANT +ATOM--WM-NORMAL-HINTS+ 40))

(PROGN (EXPORT '+ATOM--WM-SIZE-HINTS+) (DEFCONSTANT +ATOM--WM-SIZE-HINTS+ 41))

(PROGN (EXPORT '+ATOM--WM-ZOOM-HINTS+) (DEFCONSTANT +ATOM--WM-ZOOM-HINTS+ 42))

(PROGN (EXPORT '+ATOM--MIN-SPACE+) (DEFCONSTANT +ATOM--MIN-SPACE+ 43))

(PROGN (EXPORT '+ATOM--NORM-SPACE+) (DEFCONSTANT +ATOM--NORM-SPACE+ 44))

(PROGN (EXPORT '+ATOM--MAX-SPACE+) (DEFCONSTANT +ATOM--MAX-SPACE+ 45))

(PROGN (EXPORT '+ATOM--END-SPACE+) (DEFCONSTANT +ATOM--END-SPACE+ 46))

(PROGN (EXPORT '+ATOM--SUPERSCRIPT-X+) (DEFCONSTANT +ATOM--SUPERSCRIPT-X+ 47))

(PROGN (EXPORT '+ATOM--SUPERSCRIPT-Y+) (DEFCONSTANT +ATOM--SUPERSCRIPT-Y+ 48))

(PROGN (EXPORT '+ATOM--SUBSCRIPT-X+) (DEFCONSTANT +ATOM--SUBSCRIPT-X+ 49))

(PROGN (EXPORT '+ATOM--SUBSCRIPT-Y+) (DEFCONSTANT +ATOM--SUBSCRIPT-Y+ 50))

(PROGN
 (EXPORT '+ATOM--UNDERLINE-POSITION+)
 (DEFCONSTANT +ATOM--UNDERLINE-POSITION+ 51))

(PROGN
 (EXPORT '+ATOM--UNDERLINE-THICKNESS+)
 (DEFCONSTANT +ATOM--UNDERLINE-THICKNESS+ 52))

(PROGN
 (EXPORT '+ATOM--STRIKEOUT-ASCENT+)
 (DEFCONSTANT +ATOM--STRIKEOUT-ASCENT+ 53))

(PROGN
 (EXPORT '+ATOM--STRIKEOUT-DESCENT+)
 (DEFCONSTANT +ATOM--STRIKEOUT-DESCENT+ 54))

(PROGN (EXPORT '+ATOM--ITALIC-ANGLE+) (DEFCONSTANT +ATOM--ITALIC-ANGLE+ 55))

(PROGN (EXPORT '+ATOM--X-HEIGHT+) (DEFCONSTANT +ATOM--X-HEIGHT+ 56))

(PROGN (EXPORT '+ATOM--QUAD-WIDTH+) (DEFCONSTANT +ATOM--QUAD-WIDTH+ 57))

(PROGN (EXPORT '+ATOM--WEIGHT+) (DEFCONSTANT +ATOM--WEIGHT+ 58))

(PROGN (EXPORT '+ATOM--POINT-SIZE+) (DEFCONSTANT +ATOM--POINT-SIZE+ 59))

(PROGN (EXPORT '+ATOM--RESOLUTION+) (DEFCONSTANT +ATOM--RESOLUTION+ 60))

(PROGN (EXPORT '+ATOM--COPYRIGHT+) (DEFCONSTANT +ATOM--COPYRIGHT+ 61))

(PROGN (EXPORT '+ATOM--NOTICE+) (DEFCONSTANT +ATOM--NOTICE+ 62))

(PROGN (EXPORT '+ATOM--FONT-NAME+) (DEFCONSTANT +ATOM--FONT-NAME+ 63))

(PROGN (EXPORT '+ATOM--FAMILY-NAME+) (DEFCONSTANT +ATOM--FAMILY-NAME+ 64))

(PROGN (EXPORT '+ATOM--FULL-NAME+) (DEFCONSTANT +ATOM--FULL-NAME+ 65))

(PROGN (EXPORT '+ATOM--CAP-HEIGHT+) (DEFCONSTANT +ATOM--CAP-HEIGHT+ 66))

(PROGN (EXPORT '+ATOM--WM-CLASS+) (DEFCONSTANT +ATOM--WM-CLASS+ 67))

(PROGN
 (EXPORT '+ATOM--WM-TRANSIENT-FOR+)
 (DEFCONSTANT +ATOM--WM-TRANSIENT-FOR+ 68))

(DEFINE-EVENT SELECTION-REQUEST 30
 ((PAD BYTES 1) (TIMESTAMP TIME) (WINDOW OWNER) (WINDOW REQUESTOR)
  (ATOM SELECTION) (ATOM TARGET) (ATOM PROPERTY)))

(DEFINE-EVENT SELECTION-NOTIFY 31
 ((PAD BYTES 1) (TIMESTAMP TIME) (WINDOW REQUESTOR) (ATOM SELECTION)
  (ATOM TARGET) (ATOM PROPERTY)))

(PROGN
 (EXPORT '+COLORMAP-STATE--UNINSTALLED+)
 (DEFCONSTANT +COLORMAP-STATE--UNINSTALLED+ 0))

(PROGN
 (EXPORT '+COLORMAP-STATE--INSTALLED+)
 (DEFCONSTANT +COLORMAP-STATE--INSTALLED+ 1))

(PROGN (EXPORT '+COLORMAP--NONE+) (DEFCONSTANT +COLORMAP--NONE+ 0))

(DEFINE-EVENT COLORMAP-NOTIFY 32
 ((PAD BYTES 1) (WINDOW WINDOW) (COLORMAP COLORMAP) (BOOL NEW) (BYTE STATE)
  (PAD BYTES 2)))

(DEFINE-EVENT CLIENT-MESSAGE 33
 ((CARD8 FORMAT) (WINDOW WINDOW) (ATOM TYPE) (CLIENT-MESSAGE-DATA DATA)))

(PROGN (EXPORT '+MAPPING--MODIFIER+) (DEFCONSTANT +MAPPING--MODIFIER+ 0))

(PROGN (EXPORT '+MAPPING--KEYBOARD+) (DEFCONSTANT +MAPPING--KEYBOARD+ 1))

(PROGN (EXPORT '+MAPPING--POINTER+) (DEFCONSTANT +MAPPING--POINTER+ 2))

(DEFINE-EVENT MAPPING-NOTIFY 34
 ((PAD BYTES 1) (BYTE REQUEST) (KEYCODE FIRST-KEYCODE) (CARD8 COUNT)
  (PAD BYTES 1)))

(DEFINE-EVENT GE-GENERIC 35 ((PAD BYTES 22)))

(DEFINE-ERROR REQUEST 1)

(DEFINE-ERROR VALUE 2)

(DEFINE-ERROR WINDOW 3)

(DEFINE-ERROR PIXMAP 4)

(DEFINE-ERROR ATOM 5)

(DEFINE-ERROR CURSOR 6)

(DEFINE-ERROR FONT 7)

(DEFINE-ERROR MATCH 8)

(DEFINE-ERROR DRAWABLE 9)

(DEFINE-ERROR ACCESS 10)

(DEFINE-ERROR ALLOC 11)

(DEFINE-ERROR COLORMAP 12)

(DEFINE-ERROR GCONTEXT 13)

(DEFINE-ERROR IDCHOICE 14)

(DEFINE-ERROR NAME 15)

(DEFINE-ERROR LENGTH 16)

(DEFINE-ERROR IMPLEMENTATION 17)

(PROGN
 (EXPORT '+WINDOW-CLASS--COPY-FROM-PARENT+)
 (DEFCONSTANT +WINDOW-CLASS--COPY-FROM-PARENT+ 0))

(PROGN
 (EXPORT '+WINDOW-CLASS--INPUT-OUTPUT+)
 (DEFCONSTANT +WINDOW-CLASS--INPUT-OUTPUT+ 1))

(PROGN
 (EXPORT '+WINDOW-CLASS--INPUT-ONLY+)
 (DEFCONSTANT +WINDOW-CLASS--INPUT-ONLY+ 2))

(PROGN (EXPORT '+CW--BACK-PIXMAP+) (DEFCONSTANT +CW--BACK-PIXMAP+ 0))

(PROGN (EXPORT '+CW--BACK-PIXEL+) (DEFCONSTANT +CW--BACK-PIXEL+ 1))

(PROGN (EXPORT '+CW--BORDER-PIXMAP+) (DEFCONSTANT +CW--BORDER-PIXMAP+ 2))

(PROGN (EXPORT '+CW--BORDER-PIXEL+) (DEFCONSTANT +CW--BORDER-PIXEL+ 3))

(PROGN (EXPORT '+CW--BIT-GRAVITY+) (DEFCONSTANT +CW--BIT-GRAVITY+ 4))

(PROGN (EXPORT '+CW--WIN-GRAVITY+) (DEFCONSTANT +CW--WIN-GRAVITY+ 5))

(PROGN (EXPORT '+CW--BACKING-STORE+) (DEFCONSTANT +CW--BACKING-STORE+ 6))

(PROGN (EXPORT '+CW--BACKING-PLANES+) (DEFCONSTANT +CW--BACKING-PLANES+ 7))

(PROGN (EXPORT '+CW--BACKING-PIXEL+) (DEFCONSTANT +CW--BACKING-PIXEL+ 8))

(PROGN
 (EXPORT '+CW--OVERRIDE-REDIRECT+)
 (DEFCONSTANT +CW--OVERRIDE-REDIRECT+ 9))

(PROGN (EXPORT '+CW--SAVE-UNDER+) (DEFCONSTANT +CW--SAVE-UNDER+ 10))

(PROGN (EXPORT '+CW--EVENT-MASK+) (DEFCONSTANT +CW--EVENT-MASK+ 11))

(PROGN (EXPORT '+CW--DONT-PROPAGATE+) (DEFCONSTANT +CW--DONT-PROPAGATE+ 12))

(PROGN (EXPORT '+CW--COLORMAP+) (DEFCONSTANT +CW--COLORMAP+ 13))

(PROGN (EXPORT '+CW--CURSOR+) (DEFCONSTANT +CW--CURSOR+ 14))

(PROGN (EXPORT '+BACK-PIXMAP--NONE+) (DEFCONSTANT +BACK-PIXMAP--NONE+ 0))

(PROGN
 (EXPORT '+BACK-PIXMAP--PARENT-RELATIVE+)
 (DEFCONSTANT +BACK-PIXMAP--PARENT-RELATIVE+ 1))

(PROGN (EXPORT '+GRAVITY--BIT-FORGET+) (DEFCONSTANT +GRAVITY--BIT-FORGET+ 0))

(PROGN (EXPORT '+GRAVITY--WIN-UNMAP+) (DEFCONSTANT +GRAVITY--WIN-UNMAP+ 0))

(PROGN (EXPORT '+GRAVITY--NORTH-WEST+) (DEFCONSTANT +GRAVITY--NORTH-WEST+ 1))

(PROGN (EXPORT '+GRAVITY--NORTH+) (DEFCONSTANT +GRAVITY--NORTH+ 2))

(PROGN (EXPORT '+GRAVITY--NORTH-EAST+) (DEFCONSTANT +GRAVITY--NORTH-EAST+ 3))

(PROGN (EXPORT '+GRAVITY--WEST+) (DEFCONSTANT +GRAVITY--WEST+ 4))

(PROGN (EXPORT '+GRAVITY--CENTER+) (DEFCONSTANT +GRAVITY--CENTER+ 5))

(PROGN (EXPORT '+GRAVITY--EAST+) (DEFCONSTANT +GRAVITY--EAST+ 6))

(PROGN (EXPORT '+GRAVITY--SOUTH-WEST+) (DEFCONSTANT +GRAVITY--SOUTH-WEST+ 7))

(PROGN (EXPORT '+GRAVITY--SOUTH+) (DEFCONSTANT +GRAVITY--SOUTH+ 8))

(PROGN (EXPORT '+GRAVITY--SOUTH-EAST+) (DEFCONSTANT +GRAVITY--SOUTH-EAST+ 9))

(PROGN (EXPORT '+GRAVITY--STATIC+) (DEFCONSTANT +GRAVITY--STATIC+ 10))

(DEFINE-REQUEST CREATE-WINDOW 1
 ((CARD8 DEPTH) (WINDOW WID) (WINDOW PARENT) (INT16 X) (INT16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD16 BORDER-WIDTH) (CARD16 CLASS) (VISUALID VISUAL)
  (CARD32 VALUE-MASK)
  (BITCASE VALUE-MASK (+CW--BACK-PIXMAP+ (PIXMAP BACKGROUND-PIXMAP))
   (+CW--BACK-PIXEL+ (CARD32 BACKGROUND-PIXEL))
   (+CW--BORDER-PIXMAP+ (PIXMAP BORDER-PIXMAP))
   (+CW--BORDER-PIXEL+ (CARD32 BORDER-PIXEL))
   (+CW--BIT-GRAVITY+ (CARD32 BIT-GRAVITY))
   (+CW--WIN-GRAVITY+ (CARD32 WIN-GRAVITY))
   (+CW--BACKING-STORE+ (CARD32 BACKING-STORE))
   (+CW--BACKING-PLANES+ (CARD32 BACKING-PLANES))
   (+CW--BACKING-PIXEL+ (CARD32 BACKING-PIXEL))
   (+CW--OVERRIDE-REDIRECT+ (BOOL32 OVERRIDE-REDIRECT))
   (+CW--SAVE-UNDER+ (BOOL32 SAVE-UNDER))
   (+CW--EVENT-MASK+ (CARD32 EVENT-MASK))
   (+CW--DONT-PROPAGATE+ (CARD32 DO-NOT-PROPOGATE-MASK))
   (+CW--COLORMAP+ (COLORMAP COLORMAP)) (+CW--CURSOR+ (CURSOR CURSOR))))
 NIL)

(DEFINE-REQUEST CHANGE-WINDOW-ATTRIBUTES 2
 ((PAD BYTES 1) (WINDOW WINDOW) (CARD32 VALUE-MASK)
  (BITCASE VALUE-MASK (+CW--BACK-PIXMAP+ (PIXMAP BACKGROUND-PIXMAP))
   (+CW--BACK-PIXEL+ (CARD32 BACKGROUND-PIXEL))
   (+CW--BORDER-PIXMAP+ (PIXMAP BORDER-PIXMAP))
   (+CW--BORDER-PIXEL+ (CARD32 BORDER-PIXEL))
   (+CW--BIT-GRAVITY+ (CARD32 BIT-GRAVITY))
   (+CW--WIN-GRAVITY+ (CARD32 WIN-GRAVITY))
   (+CW--BACKING-STORE+ (CARD32 BACKING-STORE))
   (+CW--BACKING-PLANES+ (CARD32 BACKING-PLANES))
   (+CW--BACKING-PIXEL+ (CARD32 BACKING-PIXEL))
   (+CW--OVERRIDE-REDIRECT+ (BOOL32 OVERRIDE-REDIRECT))
   (+CW--SAVE-UNDER+ (BOOL32 SAVE-UNDER))
   (+CW--EVENT-MASK+ (CARD32 EVENT-MASK))
   (+CW--DONT-PROPAGATE+ (CARD32 DO-NOT-PROPOGATE-MASK))
   (+CW--COLORMAP+ (COLORMAP COLORMAP)) (+CW--CURSOR+ (CURSOR CURSOR))))
 NIL)

(PROGN (EXPORT '+MAP-STATE--UNMAPPED+) (DEFCONSTANT +MAP-STATE--UNMAPPED+ 0))

(PROGN
 (EXPORT '+MAP-STATE--UNVIEWABLE+)
 (DEFCONSTANT +MAP-STATE--UNVIEWABLE+ 1))

(PROGN (EXPORT '+MAP-STATE--VIEWABLE+) (DEFCONSTANT +MAP-STATE--VIEWABLE+ 2))

(DEFINE-REQUEST GET-WINDOW-ATTRIBUTES 3 ((PAD BYTES 1) (WINDOW WINDOW))
 ((CARD8 BACKING-STORE) (VISUALID VISUAL) (CARD16 CLASS) (CARD8 BIT-GRAVITY)
  (CARD8 WIN-GRAVITY) (CARD32 BACKING-PLANES) (CARD32 BACKING-PIXEL)
  (BOOL SAVE-UNDER) (BOOL MAP-IS-INSTALLED) (CARD8 MAP-STATE)
  (BOOL OVERRIDE-REDIRECT) (COLORMAP COLORMAP) (CARD32 ALL-EVENT-MASKS)
  (CARD32 YOUR-EVENT-MASK) (CARD16 DO-NOT-PROPAGATE-MASK) (PAD BYTES 2)))

(DEFINE-REQUEST DESTROY-WINDOW 4 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST DESTROY-SUBWINDOWS 5 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(PROGN (EXPORT '+SET-MODE--INSERT+) (DEFCONSTANT +SET-MODE--INSERT+ 0))

(PROGN (EXPORT '+SET-MODE--DELETE+) (DEFCONSTANT +SET-MODE--DELETE+ 1))

(DEFINE-REQUEST CHANGE-SAVE-SET 6 ((BYTE MODE) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST REPARENT-WINDOW 7
 ((PAD BYTES 1) (WINDOW WINDOW) (WINDOW PARENT) (INT16 X) (INT16 Y)) NIL)

(DEFINE-REQUEST MAP-WINDOW 8 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST MAP-SUBWINDOWS 9 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST UNMAP-WINDOW 10 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST UNMAP-SUBWINDOWS 11 ((PAD BYTES 1) (WINDOW WINDOW)) NIL)

(PROGN (EXPORT '+CONFIG-WINDOW--X+) (DEFCONSTANT +CONFIG-WINDOW--X+ 0))

(PROGN (EXPORT '+CONFIG-WINDOW--Y+) (DEFCONSTANT +CONFIG-WINDOW--Y+ 1))

(PROGN (EXPORT '+CONFIG-WINDOW--WIDTH+) (DEFCONSTANT +CONFIG-WINDOW--WIDTH+ 2))

(PROGN
 (EXPORT '+CONFIG-WINDOW--HEIGHT+)
 (DEFCONSTANT +CONFIG-WINDOW--HEIGHT+ 3))

(PROGN
 (EXPORT '+CONFIG-WINDOW--BORDER-WIDTH+)
 (DEFCONSTANT +CONFIG-WINDOW--BORDER-WIDTH+ 4))

(PROGN
 (EXPORT '+CONFIG-WINDOW--SIBLING+)
 (DEFCONSTANT +CONFIG-WINDOW--SIBLING+ 5))

(PROGN
 (EXPORT '+CONFIG-WINDOW--STACK-MODE+)
 (DEFCONSTANT +CONFIG-WINDOW--STACK-MODE+ 6))

(PROGN (EXPORT '+STACK-MODE--ABOVE+) (DEFCONSTANT +STACK-MODE--ABOVE+ 0))

(PROGN (EXPORT '+STACK-MODE--BELOW+) (DEFCONSTANT +STACK-MODE--BELOW+ 1))

(PROGN (EXPORT '+STACK-MODE--TOP-IF+) (DEFCONSTANT +STACK-MODE--TOP-IF+ 2))

(PROGN
 (EXPORT '+STACK-MODE--BOTTOM-IF+)
 (DEFCONSTANT +STACK-MODE--BOTTOM-IF+ 3))

(PROGN (EXPORT '+STACK-MODE--OPPOSITE+) (DEFCONSTANT +STACK-MODE--OPPOSITE+ 4))

(DEFINE-REQUEST CONFIGURE-WINDOW 12
 ((PAD BYTES 1) (WINDOW WINDOW) (CARD16 VALUE-MASK) (PAD BYTES 2)
  (BITCASE VALUE-MASK (+CONFIG-WINDOW--X+ (INT32 X))
   (+CONFIG-WINDOW--Y+ (INT32 Y)) (+CONFIG-WINDOW--WIDTH+ (CARD32 WIDTH))
   (+CONFIG-WINDOW--HEIGHT+ (CARD32 HEIGHT))
   (+CONFIG-WINDOW--BORDER-WIDTH+ (CARD32 BORDER-WIDTH))
   (+CONFIG-WINDOW--SIBLING+ (WINDOW SIBLING))
   (+CONFIG-WINDOW--STACK-MODE+ (CARD32 STACK-MODE))))
 NIL)

(PROGN
 (EXPORT '+CIRCULATE--RAISE-LOWEST+)
 (DEFCONSTANT +CIRCULATE--RAISE-LOWEST+ 0))

(PROGN
 (EXPORT '+CIRCULATE--LOWER-HIGHEST+)
 (DEFCONSTANT +CIRCULATE--LOWER-HIGHEST+ 1))

(DEFINE-REQUEST CIRCULATE-WINDOW 13 ((CARD8 DIRECTION) (WINDOW WINDOW)) NIL)

(DEFINE-REQUEST GET-GEOMETRY 14 ((PAD BYTES 1) (DRAWABLE DRAWABLE))
 ((CARD8 DEPTH) (WINDOW ROOT) (INT16 X) (INT16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD16 BORDER-WIDTH) (PAD BYTES 2)))

(DEFINE-REQUEST QUERY-TREE 15 ((PAD BYTES 1) (WINDOW WINDOW))
 ((PAD BYTES 1) (WINDOW ROOT) (WINDOW PARENT) (CARD16 CHILDREN-LEN)
  (PAD BYTES 14) (LIST WINDOW CHILDREN-LEN CHILDREN)))

(DEFINE-REQUEST INTERN-ATOM 16
 ((BOOL ONLY-IF-EXISTS) (CARD16 NAME-LEN) (PAD BYTES 2)
  (LIST CHAR NAME-LEN NAME))
 ((PAD BYTES 1) (ATOM ATOM)))

(DEFINE-REQUEST GET-ATOM-NAME 17 ((PAD BYTES 1) (ATOM ATOM))
 ((PAD BYTES 1) (CARD16 NAME-LEN) (PAD BYTES 22) (LIST CHAR NAME-LEN NAME)))

(PROGN (EXPORT '+PROP-MODE--REPLACE+) (DEFCONSTANT +PROP-MODE--REPLACE+ 0))

(PROGN (EXPORT '+PROP-MODE--PREPEND+) (DEFCONSTANT +PROP-MODE--PREPEND+ 1))

(PROGN (EXPORT '+PROP-MODE--APPEND+) (DEFCONSTANT +PROP-MODE--APPEND+ 2))

(DEFINE-REQUEST CHANGE-PROPERTY 18
 ((CARD8 MODE) (WINDOW WINDOW) (ATOM PROPERTY) (ATOM TYPE) (CARD8 FORMAT)
  (PAD BYTES 3) (CARD32 DATA-LEN) (LIST VOID (/ (* DATA-LEN FORMAT) 8) DATA))
 NIL)

(DEFINE-REQUEST DELETE-PROPERTY 19
 ((PAD BYTES 1) (WINDOW WINDOW) (ATOM PROPERTY)) NIL)

(PROGN
 (EXPORT '+GET-PROPERTY-TYPE--ANY+)
 (DEFCONSTANT +GET-PROPERTY-TYPE--ANY+ 0))

(DEFINE-REQUEST GET-PROPERTY 20
 ((BOOL DELETE) (WINDOW WINDOW) (ATOM PROPERTY) (ATOM TYPE)
  (CARD32 LONG-OFFSET) (CARD32 LONG-LENGTH))
 ((CARD8 FORMAT) (ATOM TYPE) (CARD32 BYTES-AFTER) (CARD32 VALUE-LEN)
  (PAD BYTES 12) (LIST VOID (* VALUE-LEN (/ FORMAT 8)) VALUE)))

(DEFINE-REQUEST LIST-PROPERTIES 21 ((PAD BYTES 1) (WINDOW WINDOW))
 ((PAD BYTES 1) (CARD16 ATOMS-LEN) (PAD BYTES 22) (LIST ATOM ATOMS-LEN ATOMS)))

(DEFINE-REQUEST SET-SELECTION-OWNER 22
 ((PAD BYTES 1) (WINDOW OWNER) (ATOM SELECTION) (TIMESTAMP TIME)) NIL)

(DEFINE-REQUEST GET-SELECTION-OWNER 23 ((PAD BYTES 1) (ATOM SELECTION))
 ((PAD BYTES 1) (WINDOW OWNER)))

(DEFINE-REQUEST CONVERT-SELECTION 24
 ((PAD BYTES 1) (WINDOW REQUESTOR) (ATOM SELECTION) (ATOM TARGET)
  (ATOM PROPERTY) (TIMESTAMP TIME))
 NIL)

(PROGN
 (EXPORT '+SEND-EVENT-DEST--POINTER-WINDOW+)
 (DEFCONSTANT +SEND-EVENT-DEST--POINTER-WINDOW+ 0))

(PROGN
 (EXPORT '+SEND-EVENT-DEST--ITEM-FOCUS+)
 (DEFCONSTANT +SEND-EVENT-DEST--ITEM-FOCUS+ 1))

(DEFINE-REQUEST SEND-EVENT 25
 ((BOOL PROPAGATE) (WINDOW DESTINATION) (CARD32 EVENT-MASK)
  (LIST CHAR 32 EVENT))
 NIL)

(PROGN (EXPORT '+GRAB-MODE--SYNC+) (DEFCONSTANT +GRAB-MODE--SYNC+ 0))

(PROGN (EXPORT '+GRAB-MODE--ASYNC+) (DEFCONSTANT +GRAB-MODE--ASYNC+ 1))

(PROGN (EXPORT '+GRAB-STATUS--SUCCESS+) (DEFCONSTANT +GRAB-STATUS--SUCCESS+ 0))

(PROGN
 (EXPORT '+GRAB-STATUS--ALREADY-GRABBED+)
 (DEFCONSTANT +GRAB-STATUS--ALREADY-GRABBED+ 1))

(PROGN
 (EXPORT '+GRAB-STATUS--INVALID-TIME+)
 (DEFCONSTANT +GRAB-STATUS--INVALID-TIME+ 2))

(PROGN
 (EXPORT '+GRAB-STATUS--NOT-VIEWABLE+)
 (DEFCONSTANT +GRAB-STATUS--NOT-VIEWABLE+ 3))

(PROGN (EXPORT '+GRAB-STATUS--FROZEN+) (DEFCONSTANT +GRAB-STATUS--FROZEN+ 4))

(PROGN (EXPORT '+CURSOR--NONE+) (DEFCONSTANT +CURSOR--NONE+ 0))

(DEFINE-REQUEST GRAB-POINTER 26
 ((BOOL OWNER-EVENTS) (WINDOW GRAB-WINDOW) (CARD16 EVENT-MASK)
  (BYTE POINTER-MODE) (BYTE KEYBOARD-MODE) (WINDOW CONFINE-TO) (CURSOR CURSOR)
  (TIMESTAMP TIME))
 ((BYTE STATUS)))

(DEFINE-REQUEST UNGRAB-POINTER 27 ((PAD BYTES 1) (TIMESTAMP TIME)) NIL)

(PROGN (EXPORT '+BUTTON-INDEX--ANY+) (DEFCONSTANT +BUTTON-INDEX--ANY+ 0))

(PROGN (EXPORT '+BUTTON-INDEX--1+) (DEFCONSTANT +BUTTON-INDEX--1+ 1))

(PROGN (EXPORT '+BUTTON-INDEX--2+) (DEFCONSTANT +BUTTON-INDEX--2+ 2))

(PROGN (EXPORT '+BUTTON-INDEX--3+) (DEFCONSTANT +BUTTON-INDEX--3+ 3))

(PROGN (EXPORT '+BUTTON-INDEX--4+) (DEFCONSTANT +BUTTON-INDEX--4+ 4))

(PROGN (EXPORT '+BUTTON-INDEX--5+) (DEFCONSTANT +BUTTON-INDEX--5+ 5))

(DEFINE-REQUEST GRAB-BUTTON 28
 ((BOOL OWNER-EVENTS) (WINDOW GRAB-WINDOW) (CARD16 EVENT-MASK)
  (CARD8 POINTER-MODE) (CARD8 KEYBOARD-MODE) (WINDOW CONFINE-TO)
  (CURSOR CURSOR) (CARD8 BUTTON) (PAD BYTES 1) (CARD16 MODIFIERS))
 NIL)

(DEFINE-REQUEST UNGRAB-BUTTON 29
 ((CARD8 BUTTON) (WINDOW GRAB-WINDOW) (CARD16 MODIFIERS) (PAD BYTES 2)) NIL)

(DEFINE-REQUEST CHANGE-ACTIVE-POINTER-GRAB 30
 ((PAD BYTES 1) (CURSOR CURSOR) (TIMESTAMP TIME) (CARD16 EVENT-MASK)
  (PAD BYTES 2))
 NIL)

(DEFINE-REQUEST GRAB-KEYBOARD 31
 ((BOOL OWNER-EVENTS) (WINDOW GRAB-WINDOW) (TIMESTAMP TIME) (BYTE POINTER-MODE)
  (BYTE KEYBOARD-MODE) (PAD BYTES 2))
 ((BYTE STATUS)))

(DEFINE-REQUEST UNGRAB-KEYBOARD 32 ((PAD BYTES 1) (TIMESTAMP TIME)) NIL)

(PROGN (EXPORT '+GRAB--ANY+) (DEFCONSTANT +GRAB--ANY+ 0))

(DEFINE-REQUEST GRAB-KEY 33
 ((BOOL OWNER-EVENTS) (WINDOW GRAB-WINDOW) (CARD16 MODIFIERS) (KEYCODE KEY)
  (CARD8 POINTER-MODE) (CARD8 KEYBOARD-MODE) (PAD BYTES 3))
 NIL)

(DEFINE-REQUEST UNGRAB-KEY 34
 ((KEYCODE KEY) (WINDOW GRAB-WINDOW) (CARD16 MODIFIERS) (PAD BYTES 2)) NIL)

(PROGN (EXPORT '+ALLOW--ASYNC-POINTER+) (DEFCONSTANT +ALLOW--ASYNC-POINTER+ 0))

(PROGN (EXPORT '+ALLOW--SYNC-POINTER+) (DEFCONSTANT +ALLOW--SYNC-POINTER+ 1))

(PROGN
 (EXPORT '+ALLOW--REPLAY-POINTER+)
 (DEFCONSTANT +ALLOW--REPLAY-POINTER+ 2))

(PROGN
 (EXPORT '+ALLOW--ASYNC-KEYBOARD+)
 (DEFCONSTANT +ALLOW--ASYNC-KEYBOARD+ 3))

(PROGN (EXPORT '+ALLOW--SYNC-KEYBOARD+) (DEFCONSTANT +ALLOW--SYNC-KEYBOARD+ 4))

(PROGN
 (EXPORT '+ALLOW--REPLAY-KEYBOARD+)
 (DEFCONSTANT +ALLOW--REPLAY-KEYBOARD+ 5))

(PROGN (EXPORT '+ALLOW--ASYNC-BOTH+) (DEFCONSTANT +ALLOW--ASYNC-BOTH+ 6))

(PROGN (EXPORT '+ALLOW--SYNC-BOTH+) (DEFCONSTANT +ALLOW--SYNC-BOTH+ 7))

(DEFINE-REQUEST ALLOW-EVENTS 35 ((CARD8 MODE) (TIMESTAMP TIME)) NIL)

(DEFINE-REQUEST GRAB-SERVER 36 NIL NIL)

(DEFINE-REQUEST UNGRAB-SERVER 37 NIL NIL)

(DEFINE-REQUEST QUERY-POINTER 38 ((PAD BYTES 1) (WINDOW WINDOW))
 ((BOOL SAME-SCREEN) (WINDOW ROOT) (WINDOW CHILD) (INT16 ROOT-X) (INT16 ROOT-Y)
  (INT16 WIN-X) (INT16 WIN-Y) (CARD16 MASK) (PAD BYTES 2)))

(DEFINE-STRUCT TIMECOORD ((TIMESTAMP TIME) (INT16 X) (INT16 Y)))

(DEFINE-REQUEST GET-MOTION-EVENTS 39
 ((PAD BYTES 1) (WINDOW WINDOW) (TIMESTAMP START) (TIMESTAMP STOP))
 ((PAD BYTES 1) (CARD32 EVENTS-LEN) (PAD BYTES 20)
  (LIST TIMECOORD EVENTS-LEN EVENTS)))

(DEFINE-REQUEST TRANSLATE-COORDINATES 40
 ((PAD BYTES 1) (WINDOW SRC-WINDOW) (WINDOW DST-WINDOW) (INT16 SRC-X)
  (INT16 SRC-Y))
 ((BOOL SAME-SCREEN) (WINDOW CHILD) (INT16 DST-X) (INT16 DST-Y)))

(DEFINE-REQUEST WARP-POINTER 41
 ((PAD BYTES 1) (WINDOW SRC-WINDOW) (WINDOW DST-WINDOW) (INT16 SRC-X)
  (INT16 SRC-Y) (CARD16 SRC-WIDTH) (CARD16 SRC-HEIGHT) (INT16 DST-X)
  (INT16 DST-Y))
 NIL)

(PROGN (EXPORT '+INPUT-FOCUS--NONE+) (DEFCONSTANT +INPUT-FOCUS--NONE+ 0))

(PROGN
 (EXPORT '+INPUT-FOCUS--POINTER-ROOT+)
 (DEFCONSTANT +INPUT-FOCUS--POINTER-ROOT+ 1))

(PROGN (EXPORT '+INPUT-FOCUS--PARENT+) (DEFCONSTANT +INPUT-FOCUS--PARENT+ 2))

(PROGN
 (EXPORT '+INPUT-FOCUS--FOLLOW-KEYBOARD+)
 (DEFCONSTANT +INPUT-FOCUS--FOLLOW-KEYBOARD+ 3))

(DEFINE-REQUEST SET-INPUT-FOCUS 42
 ((CARD8 REVERT-TO) (WINDOW FOCUS) (TIMESTAMP TIME)) NIL)

(DEFINE-REQUEST GET-INPUT-FOCUS 43 NIL ((CARD8 REVERT-TO) (WINDOW FOCUS)))

(DEFINE-REQUEST QUERY-KEYMAP 44 NIL ((PAD BYTES 1) (LIST CARD8 32 KEYS)))

(DEFINE-REQUEST OPEN-FONT 45
 ((PAD BYTES 1) (FONT FID) (CARD16 NAME-LEN) (PAD BYTES 2)
  (LIST CHAR NAME-LEN NAME))
 NIL)

(DEFINE-REQUEST CLOSE-FONT 46 ((PAD BYTES 1) (FONT FONT)) NIL)

(PROGN
 (EXPORT '+FONT-DRAW--LEFT-TO-RIGHT+)
 (DEFCONSTANT +FONT-DRAW--LEFT-TO-RIGHT+ 0))

(PROGN
 (EXPORT '+FONT-DRAW--RIGHT-TO-LEFT+)
 (DEFCONSTANT +FONT-DRAW--RIGHT-TO-LEFT+ 1))

(DEFINE-STRUCT FONTPROP ((ATOM NAME) (CARD32 VALUE)))

(DEFINE-STRUCT CHARINFO
 ((INT16 LEFT-SIDE-BEARING) (INT16 RIGHT-SIDE-BEARING) (INT16 CHARACTER-WIDTH)
  (INT16 ASCENT) (INT16 DESCENT) (CARD16 ATTRIBUTES)))

(DEFINE-REQUEST QUERY-FONT 47 ((PAD BYTES 1) (FONTABLE FONT))
 ((PAD BYTES 1) (CHARINFO MIN-BOUNDS) (PAD BYTES 4) (CHARINFO MAX-BOUNDS)
  (PAD BYTES 4) (CARD16 MIN-CHAR-OR-BYTE2) (CARD16 MAX-CHAR-OR-BYTE2)
  (CARD16 DEFAULT-CHAR) (CARD16 PROPERTIES-LEN) (BYTE DRAW-DIRECTION)
  (CARD8 MIN-BYTE1) (CARD8 MAX-BYTE1) (BOOL ALL-CHARS-EXIST)
  (INT16 FONT-ASCENT) (INT16 FONT-DESCENT) (CARD32 CHAR-INFOS-LEN)
  (LIST FONTPROP PROPERTIES-LEN PROPERTIES)
  (LIST CHARINFO CHAR-INFOS-LEN CHAR-INFOS)))

(DEFINE-REQUEST QUERY-TEXT-EXTENTS 48
 ((FONTABLE FONT) (LIST CHAR2B NIL STRING))
 ((BYTE DRAW-DIRECTION) (INT16 FONT-ASCENT) (INT16 FONT-DESCENT)
  (INT16 OVERALL-ASCENT) (INT16 OVERALL-DESCENT) (INT32 OVERALL-WIDTH)
  (INT32 OVERALL-LEFT) (INT32 OVERALL-RIGHT)))

(DEFINE-STRUCT STR ((CARD8 NAME-LEN) (LIST CHAR NAME-LEN NAME)))

(DEFINE-REQUEST LIST-FONTS 49
 ((PAD BYTES 1) (CARD16 MAX-NAMES) (CARD16 PATTERN-LEN)
  (LIST CHAR PATTERN-LEN PATTERN))
 ((PAD BYTES 1) (CARD16 NAMES-LEN) (PAD BYTES 22) (LIST STR NAMES-LEN NAMES)))

(DEFINE-REQUEST LIST-FONTS-WITH-INFO 50
 ((PAD BYTES 1) (CARD16 MAX-NAMES) (CARD16 PATTERN-LEN)
  (LIST CHAR PATTERN-LEN PATTERN))
 ((CARD8 NAME-LEN) (CHARINFO MIN-BOUNDS) (PAD BYTES 4) (CHARINFO MAX-BOUNDS)
  (PAD BYTES 4) (CARD16 MIN-CHAR-OR-BYTE2) (CARD16 MAX-CHAR-OR-BYTE2)
  (CARD16 DEFAULT-CHAR) (CARD16 PROPERTIES-LEN) (BYTE DRAW-DIRECTION)
  (CARD8 MIN-BYTE1) (CARD8 MAX-BYTE1) (BOOL ALL-CHARS-EXIST)
  (INT16 FONT-ASCENT) (INT16 FONT-DESCENT) (CARD32 REPLIES-HINT)
  (LIST FONTPROP PROPERTIES-LEN PROPERTIES) (LIST CHAR NAME-LEN NAME)))

(DEFINE-REQUEST SET-FONT-PATH 51
 ((PAD BYTES 1) (CARD16 FONT-QTY) (PAD BYTES 2) (LIST STR FONT-QTY FONT)) NIL)

(DEFINE-REQUEST GET-FONT-PATH 52 NIL
 ((PAD BYTES 1) (CARD16 PATH-LEN) (PAD BYTES 22) (LIST STR PATH-LEN PATH)))

(DEFINE-REQUEST CREATE-PIXMAP 53
 ((CARD8 DEPTH) (PIXMAP PID) (DRAWABLE DRAWABLE) (CARD16 WIDTH)
  (CARD16 HEIGHT))
 NIL)

(DEFINE-REQUEST FREE-PIXMAP 54 ((PAD BYTES 1) (PIXMAP PIXMAP)) NIL)

(PROGN (EXPORT '+GC--FUNCTION+) (DEFCONSTANT +GC--FUNCTION+ 0))

(PROGN (EXPORT '+GC--PLANE-MASK+) (DEFCONSTANT +GC--PLANE-MASK+ 1))

(PROGN (EXPORT '+GC--FOREGROUND+) (DEFCONSTANT +GC--FOREGROUND+ 2))

(PROGN (EXPORT '+GC--BACKGROUND+) (DEFCONSTANT +GC--BACKGROUND+ 3))

(PROGN (EXPORT '+GC--LINE-WIDTH+) (DEFCONSTANT +GC--LINE-WIDTH+ 4))

(PROGN (EXPORT '+GC--LINE-STYLE+) (DEFCONSTANT +GC--LINE-STYLE+ 5))

(PROGN (EXPORT '+GC--CAP-STYLE+) (DEFCONSTANT +GC--CAP-STYLE+ 6))

(PROGN (EXPORT '+GC--JOIN-STYLE+) (DEFCONSTANT +GC--JOIN-STYLE+ 7))

(PROGN (EXPORT '+GC--FILL-STYLE+) (DEFCONSTANT +GC--FILL-STYLE+ 8))

(PROGN (EXPORT '+GC--FILL-RULE+) (DEFCONSTANT +GC--FILL-RULE+ 9))

(PROGN (EXPORT '+GC--TILE+) (DEFCONSTANT +GC--TILE+ 10))

(PROGN (EXPORT '+GC--STIPPLE+) (DEFCONSTANT +GC--STIPPLE+ 11))

(PROGN
 (EXPORT '+GC--TILE-STIPPLE-ORIGIN-X+)
 (DEFCONSTANT +GC--TILE-STIPPLE-ORIGIN-X+ 12))

(PROGN
 (EXPORT '+GC--TILE-STIPPLE-ORIGIN-Y+)
 (DEFCONSTANT +GC--TILE-STIPPLE-ORIGIN-Y+ 13))

(PROGN (EXPORT '+GC--FONT+) (DEFCONSTANT +GC--FONT+ 14))

(PROGN (EXPORT '+GC--SUBWINDOW-MODE+) (DEFCONSTANT +GC--SUBWINDOW-MODE+ 15))

(PROGN
 (EXPORT '+GC--GRAPHICS-EXPOSURES+)
 (DEFCONSTANT +GC--GRAPHICS-EXPOSURES+ 16))

(PROGN (EXPORT '+GC--CLIP-ORIGIN-X+) (DEFCONSTANT +GC--CLIP-ORIGIN-X+ 17))

(PROGN (EXPORT '+GC--CLIP-ORIGIN-Y+) (DEFCONSTANT +GC--CLIP-ORIGIN-Y+ 18))

(PROGN (EXPORT '+GC--CLIP-MASK+) (DEFCONSTANT +GC--CLIP-MASK+ 19))

(PROGN (EXPORT '+GC--DASH-OFFSET+) (DEFCONSTANT +GC--DASH-OFFSET+ 20))

(PROGN (EXPORT '+GC--DASH-LIST+) (DEFCONSTANT +GC--DASH-LIST+ 21))

(PROGN (EXPORT '+GC--ARC-MODE+) (DEFCONSTANT +GC--ARC-MODE+ 22))

(PROGN (EXPORT '+GX--CLEAR+) (DEFCONSTANT +GX--CLEAR+ 0))

(PROGN (EXPORT '+GX--AND+) (DEFCONSTANT +GX--AND+ 1))

(PROGN (EXPORT '+GX--AND-REVERSE+) (DEFCONSTANT +GX--AND-REVERSE+ 2))

(PROGN (EXPORT '+GX--COPY+) (DEFCONSTANT +GX--COPY+ 3))

(PROGN (EXPORT '+GX--AND-INVERTED+) (DEFCONSTANT +GX--AND-INVERTED+ 4))

(PROGN (EXPORT '+GX--NOOP+) (DEFCONSTANT +GX--NOOP+ 5))

(PROGN (EXPORT '+GX--XOR+) (DEFCONSTANT +GX--XOR+ 6))

(PROGN (EXPORT '+GX--OR+) (DEFCONSTANT +GX--OR+ 7))

(PROGN (EXPORT '+GX--NOR+) (DEFCONSTANT +GX--NOR+ 8))

(PROGN (EXPORT '+GX--EQUIV+) (DEFCONSTANT +GX--EQUIV+ 9))

(PROGN (EXPORT '+GX--INVERT+) (DEFCONSTANT +GX--INVERT+ 10))

(PROGN (EXPORT '+GX--OR-REVERSE+) (DEFCONSTANT +GX--OR-REVERSE+ 11))

(PROGN (EXPORT '+GX--COPY-INVERTED+) (DEFCONSTANT +GX--COPY-INVERTED+ 12))

(PROGN (EXPORT '+GX--OR-INVERTED+) (DEFCONSTANT +GX--OR-INVERTED+ 13))

(PROGN (EXPORT '+GX--NAND+) (DEFCONSTANT +GX--NAND+ 14))

(PROGN (EXPORT '+GX--SET+) (DEFCONSTANT +GX--SET+ 15))

(PROGN (EXPORT '+LINE-STYLE--SOLID+) (DEFCONSTANT +LINE-STYLE--SOLID+ 0))

(PROGN
 (EXPORT '+LINE-STYLE--ON-OFF-DASH+)
 (DEFCONSTANT +LINE-STYLE--ON-OFF-DASH+ 1))

(PROGN
 (EXPORT '+LINE-STYLE--DOUBLE-DASH+)
 (DEFCONSTANT +LINE-STYLE--DOUBLE-DASH+ 2))

(PROGN (EXPORT '+CAP-STYLE--NOT-LAST+) (DEFCONSTANT +CAP-STYLE--NOT-LAST+ 0))

(PROGN (EXPORT '+CAP-STYLE--BUTT+) (DEFCONSTANT +CAP-STYLE--BUTT+ 1))

(PROGN (EXPORT '+CAP-STYLE--ROUND+) (DEFCONSTANT +CAP-STYLE--ROUND+ 2))

(PROGN
 (EXPORT '+CAP-STYLE--PROJECTING+)
 (DEFCONSTANT +CAP-STYLE--PROJECTING+ 3))

(PROGN (EXPORT '+JOIN-STYLE--MITER+) (DEFCONSTANT +JOIN-STYLE--MITER+ 0))

(PROGN (EXPORT '+JOIN-STYLE--ROUND+) (DEFCONSTANT +JOIN-STYLE--ROUND+ 1))

(PROGN (EXPORT '+JOIN-STYLE--BEVEL+) (DEFCONSTANT +JOIN-STYLE--BEVEL+ 2))

(PROGN (EXPORT '+FILL-STYLE--SOLID+) (DEFCONSTANT +FILL-STYLE--SOLID+ 0))

(PROGN (EXPORT '+FILL-STYLE--TILED+) (DEFCONSTANT +FILL-STYLE--TILED+ 1))

(PROGN (EXPORT '+FILL-STYLE--STIPPLED+) (DEFCONSTANT +FILL-STYLE--STIPPLED+ 2))

(PROGN
 (EXPORT '+FILL-STYLE--OPAQUE-STIPPLED+)
 (DEFCONSTANT +FILL-STYLE--OPAQUE-STIPPLED+ 3))

(PROGN (EXPORT '+FILL-RULE--EVEN-ODD+) (DEFCONSTANT +FILL-RULE--EVEN-ODD+ 0))

(PROGN (EXPORT '+FILL-RULE--WINDING+) (DEFCONSTANT +FILL-RULE--WINDING+ 1))

(PROGN
 (EXPORT '+SUBWINDOW-MODE--CLIP-BY-CHILDREN+)
 (DEFCONSTANT +SUBWINDOW-MODE--CLIP-BY-CHILDREN+ 0))

(PROGN
 (EXPORT '+SUBWINDOW-MODE--INCLUDE-INFERIORS+)
 (DEFCONSTANT +SUBWINDOW-MODE--INCLUDE-INFERIORS+ 1))

(PROGN (EXPORT '+ARC-MODE--CHORD+) (DEFCONSTANT +ARC-MODE--CHORD+ 0))

(PROGN (EXPORT '+ARC-MODE--PIE-SLICE+) (DEFCONSTANT +ARC-MODE--PIE-SLICE+ 1))

(DEFINE-REQUEST CREATE-GC 55
 ((PAD BYTES 1) (GCONTEXT CID) (DRAWABLE DRAWABLE) (CARD32 VALUE-MASK)
  (BITCASE VALUE-MASK (+GC--FUNCTION+ (CARD32 FUNCTION))
   (+GC--PLANE-MASK+ (CARD32 PLANE-MASK))
   (+GC--FOREGROUND+ (CARD32 FOREGROUND))
   (+GC--BACKGROUND+ (CARD32 BACKGROUND))
   (+GC--LINE-WIDTH+ (CARD32 LINE-WIDTH))
   (+GC--LINE-STYLE+ (CARD32 LINE-STYLE)) (+GC--CAP-STYLE+ (CARD32 CAP-STYLE))
   (+GC--JOIN-STYLE+ (CARD32 JOIN-STYLE))
   (+GC--FILL-STYLE+ (CARD32 FILL-STYLE)) (+GC--FILL-RULE+ (CARD32 FILL-RULE))
   (+GC--TILE+ (PIXMAP TILE)) (+GC--STIPPLE+ (PIXMAP STIPPLE))
   (+GC--TILE-STIPPLE-ORIGIN-X+ (INT32 TILE-STIPPLE-X-ORIGIN))
   (+GC--TILE-STIPPLE-ORIGIN-Y+ (INT32 TILE-STIPPLE-Y-ORIGIN))
   (+GC--FONT+ (FONT FONT)) (+GC--SUBWINDOW-MODE+ (CARD32 SUBWINDOW-MODE))
   (+GC--GRAPHICS-EXPOSURES+ (BOOL32 GRAPHICS-EXPOSURES))
   (+GC--CLIP-ORIGIN-X+ (INT32 CLIP-X-ORIGIN))
   (+GC--CLIP-ORIGIN-Y+ (INT32 CLIP-Y-ORIGIN))
   (+GC--CLIP-MASK+ (PIXMAP CLIP-MASK))
   (+GC--DASH-OFFSET+ (CARD32 DASH-OFFSET)) (+GC--DASH-LIST+ (CARD32 DASHES))
   (+GC--ARC-MODE+ (CARD32 ARC-MODE))))
 NIL)

(DEFINE-REQUEST CHANGE-GC 56
 ((PAD BYTES 1) (GCONTEXT GC) (CARD32 VALUE-MASK)
  (BITCASE VALUE-MASK (+GC--FUNCTION+ (CARD32 FUNCTION))
   (+GC--PLANE-MASK+ (CARD32 PLANE-MASK))
   (+GC--FOREGROUND+ (CARD32 FOREGROUND))
   (+GC--BACKGROUND+ (CARD32 BACKGROUND))
   (+GC--LINE-WIDTH+ (CARD32 LINE-WIDTH))
   (+GC--LINE-STYLE+ (CARD32 LINE-STYLE)) (+GC--CAP-STYLE+ (CARD32 CAP-STYLE))
   (+GC--JOIN-STYLE+ (CARD32 JOIN-STYLE))
   (+GC--FILL-STYLE+ (CARD32 FILL-STYLE)) (+GC--FILL-RULE+ (CARD32 FILL-RULE))
   (+GC--TILE+ (PIXMAP TILE)) (+GC--STIPPLE+ (PIXMAP STIPPLE))
   (+GC--TILE-STIPPLE-ORIGIN-X+ (INT32 TILE-STIPPLE-X-ORIGIN))
   (+GC--TILE-STIPPLE-ORIGIN-Y+ (INT32 TILE-STIPPLE-Y-ORIGIN))
   (+GC--FONT+ (FONT FONT)) (+GC--SUBWINDOW-MODE+ (CARD32 SUBWINDOW-MODE))
   (+GC--GRAPHICS-EXPOSURES+ (BOOL32 GRAPHICS-EXPOSURES))
   (+GC--CLIP-ORIGIN-X+ (INT32 CLIP-X-ORIGIN))
   (+GC--CLIP-ORIGIN-Y+ (INT32 CLIP-Y-ORIGIN))
   (+GC--CLIP-MASK+ (PIXMAP CLIP-MASK))
   (+GC--DASH-OFFSET+ (CARD32 DASH-OFFSET)) (+GC--DASH-LIST+ (CARD32 DASHES))
   (+GC--ARC-MODE+ (CARD32 ARC-MODE))))
 NIL)

(DEFINE-REQUEST COPY-GC 57
 ((PAD BYTES 1) (GCONTEXT SRC-GC) (GCONTEXT DST-GC) (CARD32 VALUE-MASK)) NIL)

(DEFINE-REQUEST SET-DASHES 58
 ((PAD BYTES 1) (GCONTEXT GC) (CARD16 DASH-OFFSET) (CARD16 DASHES-LEN)
  (LIST CARD8 DASHES-LEN DASHES))
 NIL)

(PROGN
 (EXPORT '+CLIP-ORDERING--UNSORTED+)
 (DEFCONSTANT +CLIP-ORDERING--UNSORTED+ 0))

(PROGN
 (EXPORT '+CLIP-ORDERING--YSORTED+)
 (DEFCONSTANT +CLIP-ORDERING--YSORTED+ 1))

(PROGN
 (EXPORT '+CLIP-ORDERING--YXSORTED+)
 (DEFCONSTANT +CLIP-ORDERING--YXSORTED+ 2))

(PROGN
 (EXPORT '+CLIP-ORDERING--YXBANDED+)
 (DEFCONSTANT +CLIP-ORDERING--YXBANDED+ 3))

(DEFINE-REQUEST SET-CLIP-RECTANGLES 59
 ((BYTE ORDERING) (GCONTEXT GC) (INT16 CLIP-X-ORIGIN) (INT16 CLIP-Y-ORIGIN)
  (LIST RECTANGLE NIL RECTANGLES))
 NIL)

(DEFINE-REQUEST FREE-GC 60 ((PAD BYTES 1) (GCONTEXT GC)) NIL)

(DEFINE-REQUEST CLEAR-AREA 61
 ((BOOL EXPOSURES) (WINDOW WINDOW) (INT16 X) (INT16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT))
 NIL)

(DEFINE-REQUEST COPY-AREA 62
 ((PAD BYTES 1) (DRAWABLE SRC-DRAWABLE) (DRAWABLE DST-DRAWABLE) (GCONTEXT GC)
  (INT16 SRC-X) (INT16 SRC-Y) (INT16 DST-X) (INT16 DST-Y) (CARD16 WIDTH)
  (CARD16 HEIGHT))
 NIL)

(DEFINE-REQUEST COPY-PLANE 63
 ((PAD BYTES 1) (DRAWABLE SRC-DRAWABLE) (DRAWABLE DST-DRAWABLE) (GCONTEXT GC)
  (INT16 SRC-X) (INT16 SRC-Y) (INT16 DST-X) (INT16 DST-Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD32 BIT-PLANE))
 NIL)

(PROGN (EXPORT '+COORD-MODE--ORIGIN+) (DEFCONSTANT +COORD-MODE--ORIGIN+ 0))

(PROGN (EXPORT '+COORD-MODE--PREVIOUS+) (DEFCONSTANT +COORD-MODE--PREVIOUS+ 1))

(DEFINE-REQUEST POLY-POINT 64
 ((BYTE COORDINATE-MODE) (DRAWABLE DRAWABLE) (GCONTEXT GC)
  (LIST POINT NIL POINTS))
 NIL)

(DEFINE-REQUEST POLY-LINE 65
 ((BYTE COORDINATE-MODE) (DRAWABLE DRAWABLE) (GCONTEXT GC)
  (LIST POINT NIL POINTS))
 NIL)

(DEFINE-STRUCT SEGMENT ((INT16 X1) (INT16 Y1) (INT16 X2) (INT16 Y2)))

(DEFINE-REQUEST POLY-SEGMENT 66
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (LIST SEGMENT NIL SEGMENTS))
 NIL)

(DEFINE-REQUEST POLY-RECTANGLE 67
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC)
  (LIST RECTANGLE NIL RECTANGLES))
 NIL)

(DEFINE-REQUEST POLY-ARC 68
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (LIST ARC NIL ARCS)) NIL)

(PROGN (EXPORT '+POLY-SHAPE--COMPLEX+) (DEFCONSTANT +POLY-SHAPE--COMPLEX+ 0))

(PROGN
 (EXPORT '+POLY-SHAPE--NONCONVEX+)
 (DEFCONSTANT +POLY-SHAPE--NONCONVEX+ 1))

(PROGN (EXPORT '+POLY-SHAPE--CONVEX+) (DEFCONSTANT +POLY-SHAPE--CONVEX+ 2))

(DEFINE-REQUEST FILL-POLY 69
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (CARD8 SHAPE)
  (CARD8 COORDINATE-MODE) (PAD BYTES 2) (LIST POINT NIL POINTS))
 NIL)

(DEFINE-REQUEST POLY-FILL-RECTANGLE 70
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC)
  (LIST RECTANGLE NIL RECTANGLES))
 NIL)

(DEFINE-REQUEST POLY-FILL-ARC 71
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (LIST ARC NIL ARCS)) NIL)

(PROGN
 (EXPORT '+IMAGE-FORMAT--XYBITMAP+)
 (DEFCONSTANT +IMAGE-FORMAT--XYBITMAP+ 0))

(PROGN
 (EXPORT '+IMAGE-FORMAT--XYPIXMAP+)
 (DEFCONSTANT +IMAGE-FORMAT--XYPIXMAP+ 1))

(PROGN
 (EXPORT '+IMAGE-FORMAT--ZPIXMAP+)
 (DEFCONSTANT +IMAGE-FORMAT--ZPIXMAP+ 2))

(DEFINE-REQUEST PUT-IMAGE 72
 ((CARD8 FORMAT) (DRAWABLE DRAWABLE) (GCONTEXT GC) (CARD16 WIDTH)
  (CARD16 HEIGHT) (INT16 DST-X) (INT16 DST-Y) (CARD8 LEFT-PAD) (CARD8 DEPTH)
  (PAD BYTES 2) (LIST BYTE NIL DATA))
 NIL)

(DEFINE-REQUEST GET-IMAGE 73
 ((CARD8 FORMAT) (DRAWABLE DRAWABLE) (INT16 X) (INT16 Y) (CARD16 WIDTH)
  (CARD16 HEIGHT) (CARD32 PLANE-MASK))
 ((CARD8 DEPTH) (VISUALID VISUAL) (PAD BYTES 20) (LIST BYTE (* LENGTH 4) DATA)))

(DEFINE-REQUEST POLY-TEXT8 74
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (INT16 X) (INT16 Y)
  (LIST BYTE NIL ITEMS))
 NIL)

(DEFINE-REQUEST POLY-TEXT16 75
 ((PAD BYTES 1) (DRAWABLE DRAWABLE) (GCONTEXT GC) (INT16 X) (INT16 Y)
  (LIST BYTE NIL ITEMS))
 NIL)

(DEFINE-REQUEST IMAGE-TEXT8 76
 ((BYTE STRING-LEN) (DRAWABLE DRAWABLE) (GCONTEXT GC) (INT16 X) (INT16 Y)
  (LIST CHAR STRING-LEN STRING))
 NIL)

(DEFINE-REQUEST IMAGE-TEXT16 77
 ((BYTE STRING-LEN) (DRAWABLE DRAWABLE) (GCONTEXT GC) (INT16 X) (INT16 Y)
  (LIST CHAR2B STRING-LEN STRING))
 NIL)

(PROGN (EXPORT '+COLORMAP-ALLOC--NONE+) (DEFCONSTANT +COLORMAP-ALLOC--NONE+ 0))

(PROGN (EXPORT '+COLORMAP-ALLOC--ALL+) (DEFCONSTANT +COLORMAP-ALLOC--ALL+ 1))

(DEFINE-REQUEST CREATE-COLORMAP 78
 ((BYTE ALLOC) (COLORMAP MID) (WINDOW WINDOW) (VISUALID VISUAL)) NIL)

(DEFINE-REQUEST FREE-COLORMAP 79 ((PAD BYTES 1) (COLORMAP CMAP)) NIL)

(DEFINE-REQUEST COPY-COLORMAP-AND-FREE 80
 ((PAD BYTES 1) (COLORMAP MID) (COLORMAP SRC-CMAP)) NIL)

(DEFINE-REQUEST INSTALL-COLORMAP 81 ((PAD BYTES 1) (COLORMAP CMAP)) NIL)

(DEFINE-REQUEST UNINSTALL-COLORMAP 82 ((PAD BYTES 1) (COLORMAP CMAP)) NIL)

(DEFINE-REQUEST LIST-INSTALLED-COLORMAPS 83 ((PAD BYTES 1) (WINDOW WINDOW))
 ((PAD BYTES 1) (CARD16 CMAPS-LEN) (PAD BYTES 22)
  (LIST COLORMAP CMAPS-LEN CMAPS)))

(DEFINE-REQUEST ALLOC-COLOR 84
 ((PAD BYTES 1) (COLORMAP CMAP) (CARD16 RED) (CARD16 GREEN) (CARD16 BLUE)
  (PAD BYTES 2))
 ((PAD BYTES 1) (CARD16 RED) (CARD16 GREEN) (CARD16 BLUE) (PAD BYTES 2)
  (CARD32 PIXEL)))

(DEFINE-REQUEST ALLOC-NAMED-COLOR 85
 ((PAD BYTES 1) (COLORMAP CMAP) (CARD16 NAME-LEN) (PAD BYTES 2)
  (LIST CHAR NAME-LEN NAME))
 ((PAD BYTES 1) (CARD32 PIXEL) (CARD16 EXACT-RED) (CARD16 EXACT-GREEN)
  (CARD16 EXACT-BLUE) (CARD16 VISUAL-RED) (CARD16 VISUAL-GREEN)
  (CARD16 VISUAL-BLUE)))

(DEFINE-REQUEST ALLOC-COLOR-CELLS 86
 ((BOOL CONTIGUOUS) (COLORMAP CMAP) (CARD16 COLORS) (CARD16 PLANES))
 ((PAD BYTES 1) (CARD16 PIXELS-LEN) (CARD16 MASKS-LEN) (PAD BYTES 20)
  (LIST CARD32 PIXELS-LEN PIXELS) (LIST CARD32 MASKS-LEN MASKS)))

(DEFINE-REQUEST ALLOC-COLOR-PLANES 87
 ((BOOL CONTIGUOUS) (COLORMAP CMAP) (CARD16 COLORS) (CARD16 REDS)
  (CARD16 GREENS) (CARD16 BLUES))
 ((PAD BYTES 1) (CARD16 PIXELS-LEN) (PAD BYTES 2) (CARD32 RED-MASK)
  (CARD32 GREEN-MASK) (CARD32 BLUE-MASK) (PAD BYTES 8)
  (LIST CARD32 PIXELS-LEN PIXELS)))

(DEFINE-REQUEST FREE-COLORS 88
 ((PAD BYTES 1) (COLORMAP CMAP) (CARD32 PLANE-MASK) (LIST CARD32 NIL PIXELS))
 NIL)

(PROGN (EXPORT '+COLOR-FLAG--RED+) (DEFCONSTANT +COLOR-FLAG--RED+ 0))

(PROGN (EXPORT '+COLOR-FLAG--GREEN+) (DEFCONSTANT +COLOR-FLAG--GREEN+ 1))

(PROGN (EXPORT '+COLOR-FLAG--BLUE+) (DEFCONSTANT +COLOR-FLAG--BLUE+ 2))

(DEFINE-STRUCT COLORITEM
 ((CARD32 PIXEL) (CARD16 RED) (CARD16 GREEN) (CARD16 BLUE) (BYTE FLAGS)
  (PAD BYTES 1)))

(DEFINE-REQUEST STORE-COLORS 89
 ((PAD BYTES 1) (COLORMAP CMAP) (LIST COLORITEM NIL ITEMS)) NIL)

(DEFINE-REQUEST STORE-NAMED-COLOR 90
 ((CARD8 FLAGS) (COLORMAP CMAP) (CARD32 PIXEL) (CARD16 NAME-LEN) (PAD BYTES 2)
  (LIST CHAR NAME-LEN NAME))
 NIL)

(DEFINE-STRUCT RGB ((CARD16 RED) (CARD16 GREEN) (CARD16 BLUE) (PAD BYTES 2)))

(DEFINE-REQUEST QUERY-COLORS 91
 ((PAD BYTES 1) (COLORMAP CMAP) (LIST CARD32 NIL PIXELS))
 ((PAD BYTES 1) (CARD16 COLORS-LEN) (PAD BYTES 22)
  (LIST RGB COLORS-LEN COLORS)))

(DEFINE-REQUEST LOOKUP-COLOR 92
 ((PAD BYTES 1) (COLORMAP CMAP) (CARD16 NAME-LEN) (PAD BYTES 2)
  (LIST CHAR NAME-LEN NAME))
 ((PAD BYTES 1) (CARD16 EXACT-RED) (CARD16 EXACT-GREEN) (CARD16 EXACT-BLUE)
  (CARD16 VISUAL-RED) (CARD16 VISUAL-GREEN) (CARD16 VISUAL-BLUE)))

(PROGN (EXPORT '+PIXMAP--NONE+) (DEFCONSTANT +PIXMAP--NONE+ 0))

(DEFINE-REQUEST CREATE-CURSOR 93
 ((PAD BYTES 1) (CURSOR CID) (PIXMAP SOURCE) (PIXMAP MASK) (CARD16 FORE-RED)
  (CARD16 FORE-GREEN) (CARD16 FORE-BLUE) (CARD16 BACK-RED) (CARD16 BACK-GREEN)
  (CARD16 BACK-BLUE) (CARD16 X) (CARD16 Y))
 NIL)

(PROGN (EXPORT '+FONT--NONE+) (DEFCONSTANT +FONT--NONE+ 0))

(DEFINE-REQUEST CREATE-GLYPH-CURSOR 94
 ((PAD BYTES 1) (CURSOR CID) (FONT SOURCE-FONT) (FONT MASK-FONT)
  (CARD16 SOURCE-CHAR) (CARD16 MASK-CHAR) (CARD16 FORE-RED) (CARD16 FORE-GREEN)
  (CARD16 FORE-BLUE) (CARD16 BACK-RED) (CARD16 BACK-GREEN) (CARD16 BACK-BLUE))
 NIL)

(DEFINE-REQUEST FREE-CURSOR 95 ((PAD BYTES 1) (CURSOR CURSOR)) NIL)

(DEFINE-REQUEST RECOLOR-CURSOR 96
 ((PAD BYTES 1) (CURSOR CURSOR) (CARD16 FORE-RED) (CARD16 FORE-GREEN)
  (CARD16 FORE-BLUE) (CARD16 BACK-RED) (CARD16 BACK-GREEN) (CARD16 BACK-BLUE))
 NIL)

(PROGN
 (EXPORT '+QUERY-SHAPE-OF--LARGEST-CURSOR+)
 (DEFCONSTANT +QUERY-SHAPE-OF--LARGEST-CURSOR+ 0))

(PROGN
 (EXPORT '+QUERY-SHAPE-OF--FASTEST-TILE+)
 (DEFCONSTANT +QUERY-SHAPE-OF--FASTEST-TILE+ 1))

(PROGN
 (EXPORT '+QUERY-SHAPE-OF--FASTEST-STIPPLE+)
 (DEFCONSTANT +QUERY-SHAPE-OF--FASTEST-STIPPLE+ 2))

(DEFINE-REQUEST QUERY-BEST-SIZE 97
 ((CARD8 CLASS) (DRAWABLE DRAWABLE) (CARD16 WIDTH) (CARD16 HEIGHT))
 ((PAD BYTES 1) (CARD16 WIDTH) (CARD16 HEIGHT)))

(DEFINE-REQUEST QUERY-EXTENSION 98
 ((PAD BYTES 1) (CARD16 NAME-LEN) (PAD BYTES 2) (LIST CHAR NAME-LEN NAME))
 ((PAD BYTES 1) (BOOL PRESENT) (CARD8 MAJOR-OPCODE) (CARD8 FIRST-EVENT)
  (CARD8 FIRST-ERROR)))

(DEFINE-REQUEST LIST-EXTENSIONS 99 NIL
 ((CARD8 NAMES-LEN) (PAD BYTES 24) (LIST STR NAMES-LEN NAMES)))

(DEFINE-REQUEST CHANGE-KEYBOARD-MAPPING 100
 ((CARD8 KEYCODE-COUNT) (KEYCODE FIRST-KEYCODE) (CARD8 KEYSYMS-PER-KEYCODE)
  (PAD BYTES 2) (LIST KEYSYM (* KEYCODE-COUNT KEYSYMS-PER-KEYCODE) KEYSYMS))
 NIL)

(DEFINE-REQUEST GET-KEYBOARD-MAPPING 101
 ((PAD BYTES 1) (KEYCODE FIRST-KEYCODE) (CARD8 COUNT))
 ((BYTE KEYSYMS-PER-KEYCODE) (PAD BYTES 24) (LIST KEYSYM LENGTH KEYSYMS)))

(PROGN
 (EXPORT '+KB--KEY-CLICK-PERCENT+)
 (DEFCONSTANT +KB--KEY-CLICK-PERCENT+ 0))

(PROGN (EXPORT '+KB--BELL-PERCENT+) (DEFCONSTANT +KB--BELL-PERCENT+ 1))

(PROGN (EXPORT '+KB--BELL-PITCH+) (DEFCONSTANT +KB--BELL-PITCH+ 2))

(PROGN (EXPORT '+KB--BELL-DURATION+) (DEFCONSTANT +KB--BELL-DURATION+ 3))

(PROGN (EXPORT '+KB--LED+) (DEFCONSTANT +KB--LED+ 4))

(PROGN (EXPORT '+KB--LED-MODE+) (DEFCONSTANT +KB--LED-MODE+ 5))

(PROGN (EXPORT '+KB--KEY+) (DEFCONSTANT +KB--KEY+ 6))

(PROGN (EXPORT '+KB--AUTO-REPEAT-MODE+) (DEFCONSTANT +KB--AUTO-REPEAT-MODE+ 7))

(PROGN (EXPORT '+LED-MODE--OFF+) (DEFCONSTANT +LED-MODE--OFF+ 0))

(PROGN (EXPORT '+LED-MODE--ON+) (DEFCONSTANT +LED-MODE--ON+ 1))

(PROGN
 (EXPORT '+AUTO-REPEAT-MODE--OFF+)
 (DEFCONSTANT +AUTO-REPEAT-MODE--OFF+ 0))

(PROGN (EXPORT '+AUTO-REPEAT-MODE--ON+) (DEFCONSTANT +AUTO-REPEAT-MODE--ON+ 1))

(PROGN
 (EXPORT '+AUTO-REPEAT-MODE--DEFAULT+)
 (DEFCONSTANT +AUTO-REPEAT-MODE--DEFAULT+ 2))

(DEFINE-REQUEST CHANGE-KEYBOARD-CONTROL 102
 ((PAD BYTES 1) (CARD32 VALUE-MASK)
  (BITCASE VALUE-MASK (+KB--KEY-CLICK-PERCENT+ (INT32 KEY-CLICK-PERCENT))
   (+KB--BELL-PERCENT+ (INT32 BELL-PERCENT))
   (+KB--BELL-PITCH+ (INT32 BELL-PITCH))
   (+KB--BELL-DURATION+ (INT32 BELL-DURATION)) (+KB--LED+ (CARD32 LED))
   (+KB--LED-MODE+ (CARD32 LED-MODE)) (+KB--KEY+ (KEYCODE32 KEY))
   (+KB--AUTO-REPEAT-MODE+ (CARD32 AUTO-REPEAT-MODE))))
 NIL)

(DEFINE-REQUEST GET-KEYBOARD-CONTROL 103 NIL
 ((BYTE GLOBAL-AUTO-REPEAT) (CARD32 LED-MASK) (CARD8 KEY-CLICK-PERCENT)
  (CARD8 BELL-PERCENT) (CARD16 BELL-PITCH) (CARD16 BELL-DURATION) (PAD BYTES 2)
  (LIST CARD8 32 AUTO-REPEATS)))

(DEFINE-REQUEST BELL 104 ((INT8 PERCENT)) NIL)

(DEFINE-REQUEST CHANGE-POINTER-CONTROL 105
 ((PAD BYTES 1) (INT16 ACCELERATION-NUMERATOR) (INT16 ACCELERATION-DENOMINATOR)
  (INT16 THRESHOLD) (BOOL DO-ACCELERATION) (BOOL DO-THRESHOLD))
 NIL)

(DEFINE-REQUEST GET-POINTER-CONTROL 106 NIL
 ((PAD BYTES 1) (CARD16 ACCELERATION-NUMERATOR)
  (CARD16 ACCELERATION-DENOMINATOR) (CARD16 THRESHOLD) (PAD BYTES 18)))

(PROGN
 (EXPORT '+BLANKING--NOT-PREFERRED+)
 (DEFCONSTANT +BLANKING--NOT-PREFERRED+ 0))

(PROGN (EXPORT '+BLANKING--PREFERRED+) (DEFCONSTANT +BLANKING--PREFERRED+ 1))

(PROGN (EXPORT '+BLANKING--DEFAULT+) (DEFCONSTANT +BLANKING--DEFAULT+ 2))

(PROGN
 (EXPORT '+EXPOSURES--NOT-ALLOWED+)
 (DEFCONSTANT +EXPOSURES--NOT-ALLOWED+ 0))

(PROGN (EXPORT '+EXPOSURES--ALLOWED+) (DEFCONSTANT +EXPOSURES--ALLOWED+ 1))

(PROGN (EXPORT '+EXPOSURES--DEFAULT+) (DEFCONSTANT +EXPOSURES--DEFAULT+ 2))

(DEFINE-REQUEST SET-SCREEN-SAVER 107
 ((PAD BYTES 1) (INT16 TIMEOUT) (INT16 INTERVAL) (CARD8 PREFER-BLANKING)
  (CARD8 ALLOW-EXPOSURES))
 NIL)

(DEFINE-REQUEST GET-SCREEN-SAVER 108 NIL
 ((PAD BYTES 1) (CARD16 TIMEOUT) (CARD16 INTERVAL) (BYTE PREFER-BLANKING)
  (BYTE ALLOW-EXPOSURES) (PAD BYTES 18)))

(PROGN (EXPORT '+HOST-MODE--INSERT+) (DEFCONSTANT +HOST-MODE--INSERT+ 0))

(PROGN (EXPORT '+HOST-MODE--DELETE+) (DEFCONSTANT +HOST-MODE--DELETE+ 1))

(PROGN (EXPORT '+FAMILY--INTERNET+) (DEFCONSTANT +FAMILY--INTERNET+ 0))

(PROGN (EXPORT '+FAMILY--DECNET+) (DEFCONSTANT +FAMILY--DECNET+ 1))

(PROGN (EXPORT '+FAMILY--CHAOS+) (DEFCONSTANT +FAMILY--CHAOS+ 2))

(PROGN
 (EXPORT '+FAMILY--SERVER-INTERPRETED+)
 (DEFCONSTANT +FAMILY--SERVER-INTERPRETED+ 5))

(PROGN (EXPORT '+FAMILY--INTERNET6+) (DEFCONSTANT +FAMILY--INTERNET6+ 6))

(DEFINE-REQUEST CHANGE-HOSTS 109
 ((CARD8 MODE) (CARD8 FAMILY) (PAD BYTES 1) (CARD16 ADDRESS-LEN)
  (LIST BYTE ADDRESS-LEN ADDRESS))
 NIL)

(DEFINE-STRUCT HOST
 ((CARD8 FAMILY) (PAD BYTES 1) (CARD16 ADDRESS-LEN)
  (LIST BYTE ADDRESS-LEN ADDRESS) (PAD ALIGN 4)))

(DEFINE-REQUEST LIST-HOSTS 110 NIL
 ((BYTE MODE) (CARD16 HOSTS-LEN) (PAD BYTES 22) (LIST HOST HOSTS-LEN HOSTS)))

(PROGN
 (EXPORT '+ACCESS-CONTROL--DISABLE+)
 (DEFCONSTANT +ACCESS-CONTROL--DISABLE+ 0))

(PROGN
 (EXPORT '+ACCESS-CONTROL--ENABLE+)
 (DEFCONSTANT +ACCESS-CONTROL--ENABLE+ 1))

(DEFINE-REQUEST SET-ACCESS-CONTROL 111 ((CARD8 MODE)) NIL)

(PROGN
 (EXPORT '+CLOSE-DOWN--DESTROY-ALL+)
 (DEFCONSTANT +CLOSE-DOWN--DESTROY-ALL+ 0))

(PROGN
 (EXPORT '+CLOSE-DOWN--RETAIN-PERMANENT+)
 (DEFCONSTANT +CLOSE-DOWN--RETAIN-PERMANENT+ 1))

(PROGN
 (EXPORT '+CLOSE-DOWN--RETAIN-TEMPORARY+)
 (DEFCONSTANT +CLOSE-DOWN--RETAIN-TEMPORARY+ 2))

(DEFINE-REQUEST SET-CLOSE-DOWN-MODE 112 ((CARD8 MODE)) NIL)

(PROGN (EXPORT '+KILL--ALL-TEMPORARY+) (DEFCONSTANT +KILL--ALL-TEMPORARY+ 0))

(DEFINE-REQUEST KILL-CLIENT 113 ((PAD BYTES 1) (CARD32 RESOURCE)) NIL)

(DEFINE-REQUEST ROTATE-PROPERTIES 114
 ((PAD BYTES 1) (WINDOW WINDOW) (CARD16 ATOMS-LEN) (INT16 DELTA)
  (LIST ATOM ATOMS-LEN ATOMS))
 NIL)

(PROGN (EXPORT '+SCREEN-SAVER--RESET+) (DEFCONSTANT +SCREEN-SAVER--RESET+ 0))

(PROGN (EXPORT '+SCREEN-SAVER--ACTIVE+) (DEFCONSTANT +SCREEN-SAVER--ACTIVE+ 1))

(DEFINE-REQUEST FORCE-SCREEN-SAVER 115 ((CARD8 MODE)) NIL)

(PROGN
 (EXPORT '+MAPPING-STATUS--SUCCESS+)
 (DEFCONSTANT +MAPPING-STATUS--SUCCESS+ 0))

(PROGN (EXPORT '+MAPPING-STATUS--BUSY+) (DEFCONSTANT +MAPPING-STATUS--BUSY+ 1))

(PROGN
 (EXPORT '+MAPPING-STATUS--FAILURE+)
 (DEFCONSTANT +MAPPING-STATUS--FAILURE+ 2))

(DEFINE-REQUEST SET-POINTER-MAPPING 116
 ((CARD8 MAP-LEN) (LIST CARD8 MAP-LEN MAP)) ((BYTE STATUS)))

(DEFINE-REQUEST GET-POINTER-MAPPING 117 NIL
 ((CARD8 MAP-LEN) (PAD BYTES 24) (LIST CARD8 MAP-LEN MAP)))

(PROGN (EXPORT '+MAP-INDEX--SHIFT+) (DEFCONSTANT +MAP-INDEX--SHIFT+ 0))

(PROGN (EXPORT '+MAP-INDEX--LOCK+) (DEFCONSTANT +MAP-INDEX--LOCK+ 1))

(PROGN (EXPORT '+MAP-INDEX--CONTROL+) (DEFCONSTANT +MAP-INDEX--CONTROL+ 2))

(PROGN (EXPORT '+MAP-INDEX--1+) (DEFCONSTANT +MAP-INDEX--1+ 3))

(PROGN (EXPORT '+MAP-INDEX--2+) (DEFCONSTANT +MAP-INDEX--2+ 4))

(PROGN (EXPORT '+MAP-INDEX--3+) (DEFCONSTANT +MAP-INDEX--3+ 5))

(PROGN (EXPORT '+MAP-INDEX--4+) (DEFCONSTANT +MAP-INDEX--4+ 6))

(PROGN (EXPORT '+MAP-INDEX--5+) (DEFCONSTANT +MAP-INDEX--5+ 7))

(DEFINE-REQUEST SET-MODIFIER-MAPPING 118
 ((CARD8 KEYCODES-PER-MODIFIER)
  (LIST KEYCODE (* KEYCODES-PER-MODIFIER 8) KEYCODES))
 ((BYTE STATUS)))

(DEFINE-REQUEST GET-MODIFIER-MAPPING 119 NIL
 ((CARD8 KEYCODES-PER-MODIFIER) (PAD BYTES 24)
  (LIST KEYCODE (* KEYCODES-PER-MODIFIER 8) KEYCODES)))

(DEFINE-REQUEST NO-OPERATION 127 NIL NIL)

